summon rex:astral_zombie ~~~
summon rex:astral_zombie ~~~
summon rex:astral_zombie ~~~
summon rex:astral_zombie ~~~
summon rex:astral_zombie ~~~
summon rex:astral_zombie ~~~
summon rex:astral_zombie ~~~
summon rex:astral_zombie ~~~
fill ~~~~~~ redstone_block