summon rex:firefire ~~8~-14
summon rex:firefire ~5~8~
summon rex:firefire ~1~8~9
summon rex:firefire ~~8~-4
summon rex:firefire ~26~8~
summon rex:firefire ~~8~23
summon rex:firefire ~~8~10
summon rex:firefire ~~8~22
summon rex:firefire ~-8~8~
summon rex:firefire ~~8~30
summon rex:firefire ~~8~-22
summon rex:firefire ~~8~-30
summon rex:firefire ~~8~12
summon rex:firefire ~~8~17
summon rex:firefire ~~8~-15
summon rex:firefire ~~8~-18
summon rex:firefire ~~8~18
summon rex:firefire ~~8~25
summon rex:firefire ~~8~10
summon rex:firefire ~~8~-10
summon rex:firefire ~~8~-2
summon rex:firefire ~~8~9
summon rex:firefire ~~8~-6
summon rex:firefire ~-9~8~
summon rex:firefire ~~8~7
summon rex:firefire ~~8~-5
summon rex:firefire ~~8~5
summon rex:firefire ~~8~7
summon rex:firefire ~~8~3
effect @p fire_resistance 10 10
summon rex:firefire ~4~8~
summon rex:firefire ~-5~8~
summon rex:firefire ~-22~8~
summon rex:firefire ~-10~8~
summon rex:firefire ~-22~8~
summon rex:firefire ~20~8~
summon rex:firefire ~22~8~
summon rex:firefire ~-22~8~
summon rex:firefire ~20~8~
summon rex:firefire ~-10~8~
summon rex:firefire ~7~8~
summon rex:firefire ~10~8~
summon rex:firefire ~-4~8~