fill ~~~1~~~2 rex:corruptedlog 1 replace log
fill ~~~-1~~~-2 rex:corruptedlog 1 replace log
fill ~1~~~2~~ rex:corruptedlog 1 replace log
fill ~-1~~~-2~~ rex:corruptedlog 1 replace log
fill ~~1~~~2~ rex:corruptedlog 1 replace log
fill ~~-1~~~-2~ rex:corruptedlog 1 replace log
fill ~~~1~~~2 rex:corruptedgrass 1 replace grass
fill ~~~-1~~~-2 rex:corruptedgrass 1 replace grass
fill ~1~~~2~~ rex:corruptedgrass 1 replace grass
fill ~-1~~~-2~~ rex:corruptedgrass 1 replace grass
fill ~~1~~~2~ rex:corruptedgrass 1 replace grass
fill ~~-1~~-2~ rex:corruptedgrass 1 replace grass
fill ~~~1~~~2 rex:corrupteddirt 1 replace dirt
fill ~~~-1~~~-2 rex:corrupteddirt 1 replace dirt
fill ~1~~~2~~ rex:corrupteddirt 1 replace dirt
fill ~-1~~~-2~~ rex:corrupteddirt 1 replace dirt
fill ~~1~~~2~ rex:corrupteddirt 1 replace dirt
fill ~~-1~~~-2~ rex:corrupteddirt 1 replace dirt
fill ~~~1~~~2 rex:witherleaves 1 replace leaves
fill ~~~-1~~~-2 rex:witherleaves 1 replace leaves
fill ~1~~~2~~ rex:witherleaves 1 replace leaves
fill ~-1~~~-2~~ rex:witherleaves 1 replace leaves
fill ~~1~~~2~ rex:witherleaves 1 replace leaves
fill ~~-1~~~-2~ rex:witherleaves 1 replace leaves
fill ~~~1~~~2 rex:corruptedstone 1 replace stone
fill ~~~-1~~~-2 rex:corruptedstone 1 replace stone
fill ~1~~~2~~ rex:corruptedstone 1 replace stone
fill ~-1~~~-2~~ rex:corruptedstone 1 replace stone
fill ~~1~~~2~ rex:corruptedstone 1 replace stone
fill ~~-1~~~-2~ rex:corruptedstone 1 replace stone
fill ~~~1~~~2 rex:corruptedcobblestone 1 replace cobblestone
fill ~~~-1~~~-2 rex:corruptedcobblestone 1 replace cobblestone
fill ~1~~~2~~ rex:corruptedcobblestone 1 replace cobblestone
fill ~-1~~~-2~~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~1~~~2~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~-1~~~-2~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~~1~~~2 rex:corruptedsand 1 replace sand
fill ~~~-1~~~-2 rex:corruptedsand 1 replace sand
fill ~1~~~2~~ rex:corruptedsand 1 replace sand
fill ~-1~~~-2~~ rex:corruptedsand 1 replace sand
fill ~~1~~~2~ rex:corruptedsand 1 replace sand
fill ~~-1~~~-2~ rex:corruptedsand 1 replace sand
fill ~~~1~~~2 rex:corruptedlog 2 replace log
fill ~~~-1~~~-2 rex:corruptedlog 2 replace log
fill ~1~~~2~~ rex:corruptedlog 2 replace log
fill ~-1~~~-2~~ rex:corruptedlog 2 replace log
fill ~~1~~~2~ rex:corruptedlog 2 replace log
fill ~~-1~~~-2~ rex:corruptedlog 2 replace log
fill ~~~1~~~2 rex:corruptedlog 3 replace log
fill ~~~-1~~~-2 rex:corruptedlog 3 replace log
fill ~1~~~2~~ rex:corruptedlog 3 replace log
fill ~-1~~~-2~~ rex:corruptedlog 3 replace log
fill ~~1~~~2~ rex:corruptedlog 3 replace log
fill ~~-1~~~-2~ rex:corruptedlog 3 replace log
fill ~~~1~~~2 rex:corruptedlog 4 replace log
fill ~~~-1~~~-2 rex:corruptedlog 4 replace log
fill ~1~~~2~~ rex:corruptedlog 4 replace log
fill ~-1~~~-2~~ rex:corruptedlog 4 replace log
fill ~~1~~~2~ rex:corruptedlog 4 replace log
fill ~~-1~~~-2~ rex:corruptedlog 4 replace log
fill ~~~1~~~2 rex:corruptedlog 5 replace log
fill ~~~-1~~~-2 rex:corruptedlog 5 replace log
fill ~1~~~2~~ rex:corruptedlog 5 replace log
fill ~-1~~~-2~~ rex:corruptedlog 5 replace log
fill ~~1~~~2~ rex:corruptedlog 5 replace log
fill ~~-1~~~-2~ rex:corruptedlog 5 replace log
fill ~~~1~~~2 rex:corruptedglass 1 replace glass
fill ~~~-1~~~-2 rex:corruptedglass 1 replace glass
fill ~1~~~2~~ rex:corruptedglass 1 replace glass
fill ~-1~~~-2~~ rex:corruptedglass 1 replace glass
fill ~~1~~~2~ rex:corruptedglass 1 replace glass
fill ~~-1~~~-2~ rex:corruptedglass 1 replace glass
fill ~~~1~~~2 rex:corruptedlog 1 replace log2
fill ~~~-1~~~-2 rex:corruptedlog 1 replace log2
fill ~1~~~2~~ rex:corruptedlog 1 replace log2
fill ~-1~~~-2~~ rex:corruptedlog 1 replace log2
fill ~~1~~~2~ rex:corruptedlog 1 replace log2
fill ~~-1~~~-2~ rex:corruptedlog 1 replace log2
fill ~~~1~~~2 rex:corruptedcraftingtable 1 replace crafting_table
fill ~~~-1~~~-2 rex:corruptedcraftingtable 1 replace crafting_table
fill ~1~~~2~~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~-1~~~-2~~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~1~~~2~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~-1~~~-2~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~~1~~~2 rex:corruptedslab 1 replace wooden_slab
fill ~~~-1~~~-2 rex:corruptedslab 1 replace wooden_slab
fill ~1~~~2~~ rex:corruptedslab 1 replace wooden_slab
fill ~-1~~~-2~~ rex:corruptedslab 1 replace wooden_slab
fill ~~1~~~2~ rex:corruptedslab 1 replace wooden_slab
fill ~~-1~~~-2~ rex:corruptedslab 1 replace wooden_slab
fill ~~~1~~~2 rex:corruptedplanks 1 replace planks 1
fill ~~~-1~~~-2 rex:corruptedplanks 1 replace planks 1
fill ~1~~~2~~ rex:corruptedplanks 1 replace planks 1
fill ~-1~~~-2~~ rex:corruptedplanks 1 replace planks 1
fill ~~1~~~2~ rex:corruptedplanks 1 replace planks 1
fill ~~-1~~~-2~ rex:corruptedplanks 1 replace planks 1
fill ~~~1~~~2 rex:corruptedsteelore 1 replace iron_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace iron_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace iron_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace iron_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace iron_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace iron_ore
fill ~~~1~~~2 rex:corruptedsteelore 1 replace coal_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace coal_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace coal_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace coal_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace coal_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace coal_ore
fill ~~~1~~~2 rex:corruptedsteelore 1 replace redstone_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace redstone_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace redstone_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace redstone_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace redstone_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace redstone_ore
fill ~~~1~~~2 rex:corruptedsteelore 1 replace gold_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace gold_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace gold_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace gold_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace gold_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace gold_ore
fill ~~~1~~~2 rex:corruptedsteelore 1 replace lapis_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace lapis_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace lapis_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace lapis_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace lapis_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace lapis_ore
fill ~~~1~~~2 rex:corruptedclay 1 replace clay
fill ~~~-1~~~-2 rex:corruptedclay 1 replace clay
fill ~1~~~2~~ rex:corruptedclay 1 replace clay
fill ~-1~~~-2~~ rex:corruptedclay 1 replace clay
fill ~~1~~~2~ rex:corruptedclay 1 replace clay
fill ~~-1~~~-2~ rex:corruptedclay 1 replace clay
fill ~~~1~~~2 rex:corruptedgravel 1 replace gravel
fill ~~~-1~~~-2 rex:corruptedgravel 1 replace gravel
fill ~1~~~2~~ rex:corruptedgravel 1 replace gravel
fill ~-1~~~-2~~ rex:corruptedgravel 1 replace gravel
fill ~~1~~~2~ rex:corruptedgravel 1 replace gravel
fill ~~-1~~~-2~ rex:corruptedgravel 1 replace gravel
fill ~~~1~~~2 rex:corruptedice 1 replace ice
fill ~~~-1~~~-2 rex:corruptedice 1 replace ice
fill ~1~~~2~~ rex:corruptedice 1 replace ice
fill ~-1~~~-2~~ rex:corruptedice 1 replace ice
fill ~~1~~~2~ rex:corruptedice 1 replace ice
fill ~~-1~~~-2~ rex:corruptedice 1 replace ice
fill ~~~1~~~2 rex:corruptedice 1 replace packed_ice
fill ~~~-1~~~-2 rex:corruptedice 1 replace packed_ice
fill ~1~~~2~~ rex:corruptedice 1 replace packed_ice
fill ~-1~~~-2~~ rex:corruptedice 1 replace packed_ice
fill ~~1~~~2~ rex:corruptedice 1 replace packed_ice
fill ~~-1~~~-2~ rex:corruptedice 1 replace packed_ice
fill ~~~1~~~2 rex:corruptedobsidian 1 replace obsidian
fill ~~~-1~~~-2 rex:corruptedobsidian1 replace obsidian
fill ~1~~~2~~ rex:corruptedobsidian 1 replace obsidian
fill ~-1~~~-2~~ rex:corruptedobsidian 1 replace obsidian
fill ~~1~~~2~ rex:corruptedobsidian 1 replace obsidian
fill ~~-1~~~-2~ rex:corruptedobsidian 1 replace obsidian
fill ~~~1~~~2 rex:corruptedsandstone 1 replace sandstone
fill ~~~-1~~~-2 rex:corruptedsandstone1 replace sandstone
fill ~1~~~2~~ rex:corruptedsandstone 1 replace sandstone
fill ~-1~~~-2~~ rex:corruptedsandstone 1 replace sandstone
fill ~~1~~~2~ rex:corruptedsandstone 1 replace sandstone
fill ~~-1~~~-2~ rex:corruptedsandstone 1 replace sandstone
fill ~~~1~~~2 rex:corruptedbookshelf 1 replace book_shelf
fill ~~~-1~~~-2 rex:corruptedbookshelf1 replace book_shelf
fill ~1~~~2~~ rex:corruptedbookshelf 1 replace book_shelf
fill ~-1~~~-2~~ rex:corruptedbookshelf 1 replace book_shelf
fill ~~1~~~2~ rex:corruptedbookshelf 1 replace book_shelf
fill ~~-1~~~-2~ rex:corruptedbookshelf 1 replace book_shelf
fill ~~~1~~~2 rex:corruptedsteelore 1 replace copper_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace copper_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace copper_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace copper_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace copper_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace copper_ore
fill ~~~1~~~2 rex:corruptedstairs 1 replace oak_stairs
fill ~~~-1~~~-2 rex:corruptedstairs 1 replace oak_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace oak_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace oak_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  oak_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace oak_stairs
fill ~~~1~~~2 rex:corruptedstairs 1 replace acacia_stairs
fill ~~~-1~~~-2 rex:corruptedstairs 1 replace acacia_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace acacia_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace acacia_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  acacia_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace acacia_stairs
fill ~~~1~~~2 rex:corruptedstairs 1 replace spruce_stairs
fill ~~~-1~~~-2 rex:corruptedstairs 1 replace spruce_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace spruce_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace spruce_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  spruce_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace spruce_stairs
fill ~~~1~~~2 rex:corruptedstairs 1 replace birch_stairs
fill ~~~-1~~~-2 rex:corruptedstairs 1 replace birch_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace birch_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace birch_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  birch_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace birch_stairs
fill ~~~1~~~2 rex:corruptedstairs 1 replace jungle_stairs
fill ~~~-1~~~-2 rex:corruptedstairs 1 replace jungle_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace jungle_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace jungle_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  jungle_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace jungle_stairs
fill ~~~1~~~2 rex:corruptedstone 1 replace deepslate
fill ~~~-1~~~-2 rex:corruptedstone 1 replace deepslate
fill ~1~~~2~~ rex:corruptedstone 1 replace deepslate
fill ~-1~~~-2~~ rex:corruptedstone 1 replace deepslate
fill ~~1~~~2~ rex:corruptedstone 1 replace  deepslate
fill ~~-1~~~-2~ rex:corruptedstone 1 replace deepslate
fill ~~~1~~~2 rex:corruptedblock 1 replace moss_block
fill ~~~-1~~~-2 rex:corruptedblock 1 replace moss_block
fill ~1~~~2~~ rex:corruptedblock 1 replace moss_block
fill ~-1~~~-2~~ rex:corruptedblock 1 replace moss_block
fill ~~1~~~2~ rex:corruptedblock 1 replace  moss_block
fill ~~-1~~~-2~ rex:corruptedblock 1 replace moss_block
fill ~~~1~~~2 rex:corruptedblock 1 replace powder_snow
fill ~~~-1~~~-2 rex:corruptedblock 1 replace powder_snow
fill ~1~~~2~~ rex:corruptedblock 1 replace powder_snow
fill ~-1~~~-2~~ rex:corruptedblock 1 replace powder_snow
fill ~~1~~~2~ rex:corruptedblock 1 replace powder_snow
fill ~~-1~~~-2~ rex:corruptedblock 1 replace powder_snow
fill ~~~1~~~2 rex:corruptedblock 1 replace anvil
fill ~~~-1~~~-2 rex:corruptedblock 1 replace anvil
fill ~1~~~2~~ rex:corruptedblock 1 replace anvil
fill ~-1~~~-2~~ rex:corruptedblock 1 replace anvil
fill ~~1~~~2~ rex:corruptedblock 1 replace anvil
fill ~~-1~~~-2~ rex:corruptedblock 1 replace anvil
fill ~~~1~~~2 rex:corruptedsteelblock 1 replace iron_block
fill ~~~-1~~~-2 rex:corruptedsteelblock1 replace iron_block
fill ~1~~~2~~ rex:corruptedsteelblock 1 replace iron_block
fill ~-1~~~-2~~ rex:corruptedsteelblock 1 replace iron_block
fill ~~1~~~2~ rex:corruptedsteelblock 1 replace iron_block
fill ~~-1~~~-2~ rex:corruptedsteelblock 1 replace iron_block
fill ~~~1~~~2 rex:corruptedsteelblock 1 replace gold_block
fill ~~~-1~~~-2 rex:corruptedsteelblock 1 replace gold_block
fill ~1~~~2~~ rex:corruptedsteelblock 1 replace gold_block
fill ~-1~~~-2~~ rex:corruptedsteelblock 1 replace gold_block
fill ~~1~~~2~ rex:corruptedsteelblock 1 replace gold_block
fill ~~-1~~~-2~ rex:corruptedsteelblock 1 replace gold_block
fill ~~~1~~~2 rex:corruptedsteelblock 1 replace copper_block
fill ~~~-1~~~-2 rex:corruptedsteelblock 1 replace copper_block
fill ~1~~~2~~ rex:corruptedsteelblock 1 replace copper_block
fill ~-1~~~-2~~ rex:corruptedsteelblock 1 replace copper_block
fill ~~1~~~2~ rex:corruptedsteelblock 1 replace copper_block
fill ~~-1~~~-2~ rex:corruptedsteelblock 1 replace copper_block
fill ~~~1~~~2 rex:corruptedsteelblock 1 replace redstone_block
fill ~~~-1~~~-2 rex:corruptedsteelblock 1 replace redstone_block
fill ~1~~~2~~ rex:corruptedsteelblock 1 replace redstone_block
fill ~-1~~~-2~~ rex:corruptedsteelblock 1 replace redstone_block
fill ~~1~~~2~ rex:corruptedsteelblock 1 replace redstone_block
fill ~~-1~~~-2~ rex:corruptedsteelblock 1 replace redstone_block
fill ~~~1~~~2 rex:corruptedsteelblock 1 replace lapis_block
fill ~~~-1~~~-2 rex:corruptedsteelblock 1 replace lapis_block
fill ~1~~~2~~ rex:corruptedsteelblock 1 replace lapis_block
fill ~-1~~~-2~~ rex:corruptedsteelblock 1 replace lapis_block
fill ~~1~~~2~ rex:corruptedsteelblock 1 replace lapis_block
fill ~~-1~~~-2~ rex:corruptedsteelblock 1 replace lapis_block
fill ~~~1~~~2 rex:puregemore 1 replace diamond_ore
fill ~~~-1~~~-2 rex:puregemore 1 replace diamond_ore
fill ~1~~~2~~ rex:puregemore 1 replace diamond_ore
fill ~-1~~~-2~~ rex:puregemore 1 replace diamond_ore
fill ~~1~~~2~ rex:puregemore 1 replace diamond_ore
fill ~~-1~~~-2~ rex:puregemore 1 replace diamond_ore
fill ~~~1~~~2 rex:puregemore 1 replace emerald_ore
fill ~~~-1~~~-2 rex:puregemore 1 replace emerald_ore
fill ~1~~~2~~ rex:puregemore 1 replace emerald_ore
fill ~-1~~~-2~~ rex:puregemore 1 replace emerald_ore
fill ~~1~~~2~ rex:puregemore 1 replace emerald_ore
fill ~~-1~~~-2~ rex:puregemore 1 replace emerald_ore
fill ~~~1~~~2 rex:corruptedmushroomstem 1 replace brown_mushroom_block
fill ~~~-1~~~-2 rex:corruptedmushroomstem 1 replace brown_mushroom_block
fill ~1~~~2~~ rex:corruptedmushroomstem 1 replace brown_mushroom_block
fill ~-1~~~-2~~ rex:corruptedmushroomstem 1 replace brown_mushroom_block
fill ~~1~~~2~ rex:corruptedmushroomstem 1 replace brown_mushroom_block
fill ~~-1~~~-2~ rex:corruptedmushroomstem 1 replace brown_mushroom_block
fill ~~~1~~~2 rex:corruptedmushroomblock 1 replace red_mushroom_block
fill ~~~-1~~~-2 rex:corruptedmushroomblock 1 replace red_mushroom_block
fill ~1~~~2~~ rex:corruptedmushroomblock 1 replace red_mushroom_block
fill ~-1~~~-2~~ rex:corruptedmushroomblock 1 replace red_mushroom_block
fill ~~1~~~2~ rex:corruptedmushroomblock 1 replace red_mushroom_block
fill ~~-1~~~-2~ rex:corruptedmushroomblock 1 replace red_mushroom_block
fill ~~~1~~~2 rex:corruptedblock 1 replace bone_block
fill ~~~-1~~~-2 rex:corruptedblock 1 replace bone_block
fill ~1~~~2~~ rex:corruptedblock 1 replace bone_block
fill ~-1~~~-2~~ rex:corruptedblock 1 replace bone_block
fill ~~1~~~2~ rex:corruptedblock 1 replace bone_block
fill ~~-1~~~-2~ rex:corruptedblock 1 replace bone_block
fill ~~~1~~~2 rex:corruptedblock 1 replace brick_block
fill ~~~-1~~~-2 rex:corruptedblock 1 replace brick_block
fill ~1~~~2~~ rex:corruptedblock 1 replace brick_block
fill ~-1~~~-2~~ rex:corruptedblock 1 replace brick_block
fill ~~1~~~2~ rex:corruptedblock 1 replace brick_block
fill ~~-1~~~-2~ rex:corruptedblock 1 replace brick_block
fill ~~~1~~~2 rex:corruptedblock 1 replace cartography_table
fill ~~~-1~~~-2 rex:corruptedblock 1 replace cartography_table
fill ~1~~~2~~ rex:corruptedblock 1 replace cartography_table
fill ~-1~~~-2~~ rex:corruptedblock 1 replace cartography_table
fill ~~1~~~2~ rex:corruptedblock 1 replace cartography_table
fill ~~-1~~~-2~ rex:corruptedblock 1 replace cartography_table
fill ~~~1~~~2 rex:corruptedblock 1 replace carved_pumpkin
fill ~~~-1~~~-2 rex:corruptedblock 1 replace carved_pumpkin
fill ~1~~~2~~ rex:corruptedblock 1 replace carved_pumpkin
fill ~-1~~~-2~~ rex:corruptedblock 1 replace carved_pumpkin
fill ~~1~~~2~ rex:corruptedblock 1 replace carved_pumpkin
fill ~~-1~~~-2~ rex:corruptedblock 1 replace carved_pumpkin
fill ~~~1~~~2 rex:corruptedblock 1 replace pumpkin
fill ~~~-1~~~-2 rex:corruptedblock 1 replace pumpkin
fill ~1~~~2~~ rex:corruptedblock 1 replace pumpkin
fill ~-1~~~-2~~ rex:corruptedblock 1 replace pumpkin
fill ~~1~~~2~ rex:corruptedblock 1 replace pumpkin
fill ~~-1~~~-2~ rex:corruptedblock 1 replace pumpkin
fill ~~~1~~~2 rex:corruptedblock 1 replace cobblestone_wall
fill ~~~-1~~~-2 rex:corruptedblock 1 replace cobblestone_wall
fill ~1~~~2~~ rex:corruptedblock 1 replace cobblestone_wall
fill ~-1~~~-2~~ rex:corruptedblock 1 replace cobblestone_wall
fill ~~1~~~2~ rex:corruptedblock 1 replace cobblestone_wall
fill ~~-1~~~-2~ rex:corruptedblock 1 replace cobblestone_wall
fill ~~~1~~~2 rex:corruptedconcrete 1 replace concrete
fill ~~~-1~~~-2 rex:corruptedconcrete 1 replace concrete
fill ~1~~~2~~ rex:corruptedconcrete 1 replace concrete
fill ~-1~~~-2~~ rex:corruptedconcrete 1 replace concrete
fill ~~1~~~2~ rex:corruptedconcrete 1 replace concrete
fill ~~-1~~~-2~ rex:corruptedconcrete 1 replace concrete
fill ~~~1~~~2 rex:corruptedsand 1 replace concretepowder
fill ~~~-1~~~-2 rex:corruptedsand 1 replace concretepowder
fill ~1~~~2~~ rex:corruptedsand 1 replace concretepowder
fill ~-1~~~-2~~ rex:corruptedsand 1 replace concretepowder
fill ~~1~~~2~ rex:corruptedsand 1 replace concretepowder
fill ~~-1~~~-2~ rex:corruptedsand 1 replace concretepowder
fill ~~~1~~~2 rex:corruptedblock 1 replace coral_block
fill ~~~-1~~~-2 rex:corruptedblock 1 replace coral_block
fill ~1~~~2~~ rex:corruptedblock 1 replace coral_block
fill ~-1~~~-2~~ rex:corruptedblock 1 replace coral_block
fill ~~1~~~2~ rex:corruptedblock 1 replace coral_block
fill ~~-1~~~-2~ rex:corruptedblock 1 replace coral_block
fill ~~~1~~~2 rex:corruptedobsidian 1 replace crying_obsidian
fill ~~~-1~~~-2 rex:corruptedobsidian 1 replace crying_obsidian
fill ~1~~~2~~ rex:corruptedobsidian 1 replace crying_obsidian
fill ~-1~~~-2~~ rex:corruptedobsidian 1 replace crying_obsidian
fill ~~1~~~2~ rex:corruptedobsidian 1 replace crying_obsidian
fill ~~-1~~~-2~ rex:corruptedobsidian 1 replace crying_obsidian
fill ~~~1~~~2 rex:puregemblock 1 replace diamond_block
fill ~~~-1~~~-2 rex:puregemblock 1 replace  diamond_block
fill ~1~~~2~~ rex:puregemblock 1 replace diamond_block
fill ~-1~~~-2~~ rex:puregemblock 1 replace diamond_block
fill ~~1~~~2~ rex:puregemblock 1 replace diamond_block
fill ~~-1~~~-2~ rex:puregemblock 1 replace diamond_block
fill ~~~1~~~2 rex:puregemblock 1 replace emerald_block
fill ~~~-1~~~-2 rex:puregemblock 1 replace  emerald_block
fill ~1~~~2~~ rex:puregemblock 1 replace emerald_block
fill ~-1~~~-2~~ rex:puregemblock 1 replace emerald_block
fill ~~1~~~2~ rex:puregemblock 1 replace emerald_block
fill ~~-1~~~-2~ rex:puregemblock 1 replace emerald_block
fill ~~~1~~~2 rex:corruptedstone 1 replace dispenser
fill ~~~-1~~~-2 rex:corruptedstone 1 replace  dispenser
fill ~1~~~2~~ rex:corruptedstone 1 replace dispenser
fill ~-1~~~-2~~ rex:corruptedstone 1 replace dispenser
fill ~~1~~~2~ rex:corruptedstone 1 replace dispenser
fill ~~-1~~~-2~ rex:corruptedstone 1 replace dispenser
fill ~~~1~~~2 rex:corruptedstone 1 replace dropper
fill ~~~-1~~~-2 rex:corruptedstone 1 replace  dropper
fill ~1~~~2~~ rex:corruptedstone 1 replace dropper
fill ~-1~~~-2~~ rex:corruptedstone 1 replace dropper
fill ~~1~~~2~ rex:corruptedstone 1 replace dropper
fill ~~-1~~~-2~ rex:corruptedstone 1 replace dropper
fill ~~~1~~~2 rex:corruptedblock 1 replace fence
fill ~~~-1~~~-2 rex:corruptedblock 1 replace fence
fill ~1~~~2~~ rex:corruptedblock 1 replace fence
fill ~-1~~~-2~~ rex:corruptedblock 1 replace fence
fill ~~1~~~2~ rex:corruptedblock 1 replace fence
fill ~~-1~~~-2~ rex:corruptedblock 1 replace fence
fill ~~~1~~~2 rex:corruptedblock 1 replace fletching_table
fill ~~~-1~~~-2 rex:corruptedblock 1 replace fletching_table
fill ~1~~~2~~ rex:corruptedblock 1 replace fletching_table
fill ~-1~~~-2~~ rex:corruptedblock 1 replace fletching_table
fill ~~1~~~2~ rex:corruptedblock 1 replace fletching_table
fill ~~-1~~~-2~ rex:corruptedblock 1 replace fletching_table
fill ~~~1~~~2 rex:corruptedgrasspath 1 replace grass_path
fill ~~~-1~~~-2 rex:corruptedgrasspath 1 replace grass_path
fill ~1~~~2~~ rex:corruptedgrasspath 1 replace grass_path
fill ~-1~~~-2~~ rex:corruptedgrasspath 1 replace grass_path
fill ~~1~~~2~ rex:corruptedgrasspath 1 replace grass_path
fill ~~-1~~~-2~ rex:corruptedgrasspath 1 replace grass_path
fill ~~~1~~~2 rex:corruptedconcrete 1 replace hardened_clay
fill ~~~-1~~~-2 rex:corruptedconcrete 1 replace hardened_clay
fill ~1~~~2~~ rex:corruptedconcrete 1 replace hardened_clay
fill ~-1~~~-2~~ rex:corruptedconcrete 1 replace hardened_clay
fill ~~1~~~2~ rex:corruptedconcrete 1 replace hardened_clay
fill ~~-1~~~-2~ rex:corruptedconcrete 1 replace hardened_clay
fill ~~~1~~~2 rex:corruptedslime 1 replace honey_block
fill ~~~-1~~~-2 rex:corruptedslime 1 replace honey_block
fill ~1~~~2~~ rex:corruptedslime 1 replace honey_block
fill ~-1~~~-2~~ rex:corruptedslime 1 replace honey_block
fill ~~1~~~2~ rex:corruptedslime 1 replace honey_block
fill ~~-1~~~-2~ rex:corruptedslime 1 replace honey_block
fill ~~~1~~~2 rex:corruptedblock 1 replace melon_block
fill ~~~-1~~~-2 rex:corruptedblock 1 replace melon_block
fill ~1~~~2~~ rex:corruptedblock 1 replace melon_block
fill ~-1~~~-2~~ rex:corruptedblock 1 replace melon_block
fill ~~1~~~2~ rex:corruptedblock 1 replace melon_block
fill ~~-1~~~-2~ rex:corruptedblock 1 replace melon_block
fill ~~~1~~~2 rex:corruptedcobblestone 1 replace mossy_cobblestone
fill ~~~-1~~~-2 rex:corruptedcobblestone 1 replace mossy_cobblestone
fill ~1~~~2~~ rex:corruptedcobblestone 1 replace mossy_cobblestone
fill ~-1~~~-2~~ rex:corruptedcobblestone 1 replace mossy_cobblestone
fill ~~1~~~2~ rex:corruptedcobblestone 1 replace mossy_cobblestone
fill ~~-1~~~-2~ rex:corruptedcobblestone 1 replace mossy_cobblestone
fill ~~~1~~~2 rex:coblestairs 1 replace mossy_cobblestone_stairs
fill ~~~-1~~~-2 rex:coblestairs 1 replace mossy_cobblestone_stairs
fill ~1~~~2~~ rex:coblestairs 1 replace mossy_cobblestone_stairs
fill ~-1~~~-2~~ rex:coblestairs 1 replace mossy_cobblestone_stairs
fill ~~1~~~2~ rex:coblestairs 1 replace mossy_cobblestone_stairs
fill ~~-1~~~-2~ rex:coblestairs 1 replace mossy_cobblestone_stairs
fill ~~~1~~~2 rex:coblestairs 1 replace mossy_stone_brick_stairs
fill ~~~-1~~~-2 rex:coblestairs 1 replace mossy_stone_brick_stairs
fill ~1~~~2~~ rex:coblestairs 1 replace mossy_stone_brick_stairs
fill ~-1~~~-2~~ rex:coblestairs 1 replace mossy_stone_brick_stairs
fill ~~1~~~2~ rex:coblestairs 1 replace mossy_stone_brick_stairs
fill ~~-1~~~-2~ rex:coblestairs 1 replace mossy_stone_brick_stairs
fill ~~~1~~~2 rex:corruptedgrass 1 replace mycelium
fill ~~~-1~~~-2 rex:corruptedgrass 1 replace mycelium
fill ~1~~~2~~ rex:corruptedgrass 1 replace mycelium
fill ~-1~~~-2~~ rex:corruptedgrass 1 replace mycelium
fill ~~1~~~2~ rex:corruptedgrass 1 replace mycelium
fill ~~-1~~~-2~ rex:corruptedgrass 1 replace mycelium
fill ~~~1~~~2 rex:coblestairs 1 replace normal_stone_stairs
fill ~~~-1~~~-2 rex:coblestairs 1 replace normal_stone_stairs
fill ~1~~~2~~ rex:coblestairs 1 replace normal_stone_stairs
fill ~-1~~~-2~~ rex:coblestairs 1 replace normal_stone_stairs
fill ~~1~~~2~ rex:coblestairs 1 replace normal_stone_stairs
fill ~~-1~~~-2~ rex:coblestairs 1 replace normal_stone_stairs
fill ~~~1~~~2 rex:corruptedblock 1 replace note_block
fill ~~~-1~~~-2 rex:corruptedblock 1 replace note_block
fill ~1~~~2~~ rex:corruptedblock 1 replace note_block
fill ~-1~~~-2~~ rex:corruptedblock 1 replace note_block
fill ~~1~~~2~ rex:corruptedblock 1 replace note_block
fill ~~-1~~~-2~ rex:corruptedblock 1 replace note_block
fill ~~~1~~~2 rex:corruptedgrass 1 replace podzol
fill ~~~-1~~~-2 rex:corruptedgrass 1 replace podzol
fill ~1~~~2~~ rex:corruptedgrass 1 replace podzol
fill ~-1~~~-2~~ rex:corruptedgrass 1 replace podzol
fill ~~1~~~2~ rex:corruptedgrass 1 replace podzol
fill ~~-1~~~-2~ rex:corruptedgrass 1 replace podzol
fill ~~~1~~~2 rex:coblestairs 1 replace polished_andesite_stairs
fill ~~~-1~~~-2 rex:coblestairs 1 replace polished_andesite_stairs
fill ~1~~~2~~ rex:coblestairs 1 replace polished_andesite_stairs
fill ~-1~~~-2~~ rex:coblestairs 1 replace polished_andesite_stairs
fill ~~1~~~2~ rex:coblestairs 1 replace polished_andesite_stairs
fill ~~-1~~~-2~ rex:coblestairs 1 replace polished_andesite_stairs
fill ~~~1~~~2 rex:coblestairs 1 replace polished_diorite_stairs
fill ~~~-1~~~-2 rex:coblestairs 1 replace polished_diorite_stairs
fill ~1~~~2~~ rex:coblestairs 1 replace polished_diorite_stairs
fill ~-1~~~-2~~ rex:coblestairs 1 replace polished_diorite_stairs
fill ~~1~~~2~ rex:coblestairs 1 replace polished_diorite_stairs
fill ~~-1~~~-2~ rex:coblestairs 1 replace polished_diorite_stairs
fill ~~~1~~~2 rex:coblestairs 1 replace polished_granite_stairs
fill ~~~-1~~~-2 rex:coblestairs 1 replace polished_granite_stairs
fill ~1~~~2~~ rex:coblestairs 1 replace polished_granite_stairs
fill ~-1~~~-2~~ rex:coblestairs 1 replace polished_granite_stairs
fill ~~1~~~2~ rex:coblestairs 1 replace polished_granite_stairs
fill ~~-1~~~-2~ rex:coblestairs 1 replace polished_granite_stairs
fill ~~~1~~~2 rex:corruptedblock 1 replace prismarine
fill ~~~-1~~~-2 rex:corruptedblock 1 replace prismarine
fill ~1~~~2~~ rex:corruptedblock 1 replace prismarine
fill ~-1~~~-2~~ rex:corruptedblock 1 replace prismarine
fill ~~1~~~2~ rex:corruptedblock 1 replace prismarine
fill ~~-1~~~-2~ rex:corruptedblock 1 replace prismarine
fill ~~~1~~~2 rex:corruptedsandstone 1 replace red_sandstone
fill ~~~-1~~~-2 rex:corruptedsandstone 1 replace red_sandstone
fill ~1~~~2~~ rex:corruptedsandstone 1 replace red_sandstone
fill ~-1~~~-2~~ rex:corruptedsandstone 1 replace red_sandstone
fill ~~1~~~2~ rex:corruptedsandstone 1 replace red_sandstone
fill ~~-1~~~-2~ rex:corruptedsandstone 1 replace red_sandstone
fill ~~~1~~~2 rex:corruptedblock 1 replace redstone_lamp
fill ~~~-1~~~-2 rex:corruptedblock 1 replace redstone_lamp
fill ~1~~~2~~ rex:corruptedblock 1 replace redstone_lamp
fill ~-1~~~-2~~ rex:corruptedblock 1 replace redstone_lamp
fill ~~1~~~2~ rex:corruptedblock 1 replace redstone_lamp
fill ~~-1~~~-2~ rex:corruptedblock 1 replace redstone_lamp
fill ~~~1~~~2 rex:corruptedsandstairs 1 replace sandstone_stairs
fill ~~~-1~~~-2 rex:corruptedsandstairs 1 replace sandstone_stairs
fill ~1~~~2~~ rex:corruptedsandstairs 1 replace sandstone_stairs
fill ~-1~~~-2~~ rex:corruptedsandstairs 1 replace sandstone_stairs
fill ~~1~~~2~ rex:corruptedsandstairs 1 replace sandstone_stairs
fill ~~-1~~~-2~ rex:corruptedsandstairs 1 replace sandstone_stairs
fill ~~~1~~~2 rex:corruptedblock 1 replace shulker_box
fill ~~~-1~~~-2 rex:corruptedblock 1 replace shulker_box
fill ~1~~~2~~ rex:corruptedblock 1 replace shulker_box
fill ~-1~~~-2~~ rex:corruptedblock 1 replace shulker_box
fill ~~1~~~2~ rex:corruptedblock 1 replace shulker_box
fill ~~-1~~~-2~ rex:corruptedblock 1 replace shulker_box
fill ~~~1~~~2 rex:corruptedblock 1 replace smithing_table
fill ~~~-1~~~-2 rex:corruptedblock 1 replace smithing_table
fill ~1~~~2~~ rex:corruptedblock 1 replace smithing_table
fill ~-1~~~-2~~ rex:corruptedblock 1 replace smithing_table
fill ~~1~~~2~ rex:corruptedblock 1 replace smithing_table
fill ~~-1~~~-2~ rex:corruptedblock 1 replace smithing_table
fill ~~~1~~~2 rex:corruptedblock 1 replace smoker
fill ~~~-1~~~-2 rex:corruptedblock 1 replace smoker
fill ~1~~~2~~ rex:corruptedblock 1 replace smoker
fill ~-1~~~-2~~ rex:corruptedblock 1 replace smoker
fill ~~1~~~2~ rex:corruptedblock 1 replace smoker
fill ~~-1~~~-2~ rex:corruptedblock 1 replace smoker
fill ~~~1~~~2 rex:corruptedsandstairs 1 replace smooth_sandstone_stairs
fill ~~~-1~~~-2 rex:corruptedsandstairs 1 replace smooth_sandstone_stairs
fill ~1~~~2~~ rex:corruptedsandstairs 1 replace smooth_sandstone_stairs
fill ~-1~~~-2~~ rex:corruptedsandstairs 1 replace smooth_sandstone_stairs
fill ~~1~~~2~ rex:corruptedsandstairs 1 replace smooth_sandstone_stairs
fill ~~-1~~~-2~ rex:corruptedsandstairs 1 replace smooth_sandstone_stairs
fill ~~~1~~~2 rex:corruptedsandstairs 1 replace smooth_red_sandstone_stairs
fill ~~~-1~~~-2 rex:corruptedsandstairs 1 replace smooth_red_sandstone_stairs
fill ~1~~~2~~ rex:corruptedsandstairs 1 replace smooth_red_sandstone_stairs
fill ~-1~~~-2~~ rex:corruptedsandstairs 1 replace smooth_red_sandstone_stairs
fill ~~1~~~2~ rex:corruptedsandstairs 1 replace smooth_red_sandstone_stairs
fill ~~-1~~~-2~ rex:corruptedsandstairs 1 replace smooth_red_sandstone_stairs
fill ~~~1~~~2 rex:corruptedstone 1 replace smooth_stone
fill ~~~-1~~~-2 rex:corruptedstone 1 replace smooth_stone
fill ~1~~~2~~ rex:corruptedstone 1 replace smooth_stone
fill ~-1~~~-2~~ rex:corruptedstone 1 replace smooth_stone
fill ~~1~~~2~ rex:corruptedstone 1 replace smooth_stone
fill ~~-1~~~-2~ rex:corruptedstone 1 replace smooth_stone
fill ~~~1~~~2 rex:corruptedblock 1 replace snow
fill ~~~-1~~~-2 rex:corruptedblock 1 replace snow
fill ~1~~~2~~ rex:corruptedblock 1 replace snow
fill ~-1~~~-2~~ rex:corruptedblock 1 replace snow
fill ~~1~~~2~ rex:corruptedblock 1 replace snow
fill ~~-1~~~-2~ rex:corruptedblock 1 replace snow
fill ~~~1~~~2 rex:corruptedblock 1 replace sponge
fill ~~~-1~~~-2 rex:corruptedblock 1 replace sponge
fill ~1~~~2~~ rex:corruptedblock 1 replace sponge
fill ~-1~~~-2~~ rex:corruptedblock 1 replace sponge
fill ~~1~~~2~ rex:corruptedblock 1 replace sponge
fill ~~-1~~~-2~ rex:corruptedblock 1 replace sponge
fill ~~~1~~~2 rex:corruptedblock 1 replace sticky_piston
fill ~~~-1~~~-2 rex:corruptedblock 1 replace sticky_piston
fill ~1~~~2~~ rex:corruptedblock 1 replace sticky_piston
fill ~-1~~~-2~~ rex:corruptedblock 1 replace sticky_piston
fill ~~1~~~2~ rex:corruptedblock 1 replace sticky_piston
fill ~~-1~~~-2~ rex:corruptedblock 1 replace sticky_piston
fill ~~~1~~~2 rex:corruptedconcrete 1 replace stained_hardened_clay
fill ~~~-1~~~-2 rex:corruptedconcrete 1 replace stained_hardened_clay
fill ~1~~~2~~ rex:corruptedconcrete 1 replace stained_hardened_clay
fill ~-1~~~-2~~ rex:corruptedconcrete 1 stained_hardened_clay
fill ~~1~~~2~ rex:corruptedconcrete 1 replace stained_hardened_clay
fill ~~-1~~~-2~ rex:corruptedconcrete 1 replace stained_hardened_clay
fill ~~~1~~~2 rex:corruptedglass 1 replace stained_glass
fill ~~~-1~~~-2 rex:corruptedglass 1 replace stained_glass
fill ~1~~~2~~ rex:corruptedglass 1 replace stained_glass
fill ~-1~~~-2~~ rex:corruptedglass 1 stained_glass
fill ~~1~~~2~ rex:corruptedglass 1 replace stained_glass
fill ~~-1~~~-2~ rex:corruptedglass 1 replace stained_glass
fill ~~~1~~~2 rex:corruptedglass 1 replace stained_glass_pane
fill ~~~-1~~~-2 rex:corruptedglass 1 replace stained_glass_pane
fill ~1~~~2~~ rex:corruptedglass 1 replace stained_glass_pane
fill ~-1~~~-2~~ rex:corruptedglass 1 stained_glass_pane
fill ~~1~~~2~ rex:corruptedglass 1 replace stained_glass_pane
fill ~~-1~~~-2~ rex:corruptedglass 1 replace stained_glass_pane
fill ~~~1~~~2 rex:coblestairs 1 replace stone_brick_stairs
fill ~~~-1~~~-2 rex:coblestairs 1 replace stone_brick_stairs
fill ~1~~~2~~ rex:coblestairs 1 replace stone_brick_stairs
fill ~-1~~~-2~~ rex:coblestairs 1 stone_brick_stairs
fill ~~1~~~2~ rex:coblestairs 1 replace stone_brick_stairs
fill ~~-1~~~-2~ rex:coblestairs 1 replace stone_brick_stairs
fill ~~~1~~~2 rex:corruptedcobblestondslab 1 replace stone_slab
fill ~~~-1~~~-2 rex:corruptedcobblestondslab 1 replace stone_slab
fill ~1~~~2~~ rex:corruptedcobblestondslab 1 replace stone_slab
fill ~-1~~~-2~~ rex:corruptedcobblestondslab 1 replace stone_slab
fill ~~1~~~2~ rex:corruptedcobblestondslab 1 replace stone_slab
fill ~~-1~~~-2~ rex:corruptedcobblestondslab 1 replace stone_slab
fill ~~~1~~~2 rex:corruptedcobblestondslab 1 replace stone_slab2
fill ~~~-1~~~-2 rex:corruptedcobblestondslab 1 replace stone_slab2
fill ~1~~~2~~ rex:corruptedcobblestondslab 1 replace stone_slab2
fill ~-1~~~-2~~ rex:corruptedcobblestondslab 1 replace stone_slab2
fill ~~1~~~2~ rex:corruptedcobblestondslab 1 replace stone_slab2
fill ~~-1~~~-2~ rex:corruptedcobblestondslab 1 replace stone_slab2
fill ~~~1~~~2 rex:corruptedcobblestondslab 1 replace stone_slab3
fill ~~~-1~~~-2 rex:corruptedcobblestondslab 1 replace stone_slab3
fill ~1~~~2~~ rex:corruptedcobblestondslab 1 replace stone_slab3
fill ~-1~~~-2~~ rex:corruptedcobblestondslab 1 replace stone_slab3
fill ~~1~~~2~ rex:corruptedcobblestondslab 1 replace stone_slab3
fill ~~-1~~~-2~ rex:corruptedcobblestondslab 1 replace stone_slab3
fill ~~~1~~~2 rex:corruptedcobblestondslab 1 replace stone_slab4
fill ~~~-1~~~-2 rex:corruptedcobblestondslab 1 replace stone_slab4
fill ~1~~~2~~ rex:corruptedcobblestondslab 1 replace stone_slab4
fill ~-1~~~-2~~ rex:corruptedcobblestondslab 1 replace stone_slab4
fill ~~1~~~2~ rex:corruptedcobblestondslab 1 replace stone_slab4
fill ~~-1~~~-2~ rex:corruptedcobblestondslab 1 replace stone_slab4
fill ~~~1~~~2 rex:corruptedstonebrick 1 replace stonebrick
fill ~~~-1~~~-2 rex:corruptedstonebrick 1 replace stonebrick
fill ~1~~~2~~ rex:corruptedstonebrick 1 replace stonebrick
fill ~-1~~~-2~~ rex:corruptedstonebrick 1 replace stonebrick
fill ~~1~~~2~ rex:corruptedstonebrick 1 replace stonebrick
fill ~~-1~~~-2~ rex:corruptedstonebrick 1 replace stonebrick
fill ~~~1~~~2 rex:corruptedstone 1 replace stonecutter_block
fill ~~~-1~~~-2 rex:corruptedstone 1 replace stonecutter_block
fill ~1~~~2~~ rex:corruptedstone 1 replace stonecutter_block
fill ~-1~~~-2~~ rex:corruptedstone 1 replace stonecutter_block
fill ~~1~~~2~ rex:corruptedstone 1 replace stonecutter_block
fill ~~-1~~~-2~ rex:corruptedstone 1 replace stonecutter_block
fill ~~~1~~~2 rex:corruptedlog 1 replace stripped_acacia_log
fill ~~~-1~~~-2 rex:corruptedlog 1 replace stripped_acacia_log
fill ~1~~~2~~ rex:corruptedlog 1 replace stripped_acacia_log
fill ~-1~~~-2~~ rex:corruptedlog 1 replace stripped_acacia_log
fill ~~1~~~2~ rex:corruptedlog 1 replace stripped_acacia_log
fill ~~-1~~~-2~ rex:corruptedlog 1 replace stripped_acacia_log
fill ~~~1~~~2 rex:corruptedlog 1 replace stripped_birch_log
fill ~~~-1~~~-2 rex:corruptedlog 1 replace stripped_birch_log
fill ~1~~~2~~ rex:corruptedlog 1 replace stripped_birch_log
fill ~-1~~~-2~~ rex:corruptedlog 1 replace stripped_birch_log
fill ~~1~~~2~ rex:corruptedlog 1 replace stripped_birch_log
fill ~~-1~~~-2~ rex:corruptedlog 1 replace stripped_birch_log
fill ~~~1~~~2 rex:corruptedlog 1 replace stripped_jungle_log
fill ~~~-1~~~-2 rex:corruptedlog 1 replace stripped_jungle_log
fill ~1~~~2~~ rex:corruptedlog 1 replace stripped_jungle_log
fill ~-1~~~-2~~ rex:corruptedlog 1 replace stripped_jungle_log
fill ~~1~~~2~ rex:corruptedlog 1 replace stripped_jungle_log
fill ~~-1~~~-2~ rex:corruptedlog 1 replace stripped_jungle_log
fill ~~~1~~~2 rex:corruptedlog 1 replace stripped_oak_log
fill ~~~-1~~~-2 rex:corruptedlog 1 replace stripped_oak_log
fill ~1~~~2~~ rex:corruptedlog 1 replace stripped_oak_log
fill ~-1~~~-2~~ rex:corruptedlog 1 replace stripped_oak_log
fill ~~1~~~2~ rex:corruptedlog 1 replace stripped_oak_log
fill ~~-1~~~-2~ rex:corruptedlog 1 replace stripped_oak_log
fill ~~~1~~~2 rex:corruptedlog 1 replace stripped_spruce_log
fill ~~~-1~~~-2 rex:corruptedlog 1 replace stripped_spruce_log
fill ~1~~~2~~ rex:corruptedlog 1 replace stripped_spruce_log
fill ~-1~~~-2~~ rex:corruptedlog 1 replace stripped_spruce_log
fill ~~1~~~2~ rex:corruptedlog 1 replace stripped_spruce_log
fill ~~-1~~~-2~ rex:corruptedlog 1 replace stripped_spruce_log
fill ~~~1~~~2 rex:corruptedlog 1 replace wood
fill ~~~-1~~~-2 rex:corruptedlog 1 replace wood
fill ~1~~~2~~ rex:corruptedlog 1 replace wood
fill ~-1~~~-2~~ rex:corruptedlog 1 replace wood
fill ~~1~~~2~ rex:corruptedlog 1 replace wood
fill ~~-1~~~-2~ rex:corruptedlog 1 replace wood
fill ~~~1~~~2 rex:corruptedslab 1 replace wooden_slab
fill ~~~-1~~~-2 rex:corruptedslab 1 replace wooden_slab
fill ~1~~~2~~ rex:corruptedslab 1 replace wooden_slab
fill ~-1~~~-2~~ rex:corruptedslab 1 replace wooden_slab
fill ~~1~~~2~ rex:corruptedslab 1 replace wooden_slab
fill ~~-1~~~-2~ rex:corruptedslab 1 replace wooden_slab
fill ~~~1~~~2 rex:corruptedwool 1 replace wool
fill ~~~-1~~~-2 rex:corruptedwool 1 replace wool
fill ~1~~~2~~ rex:corruptedwool 1 replace wool
fill ~-1~~~-2~~ rex:corruptedwool 1 replace wool
fill ~~1~~~2~ rex:corruptedwool 1 replace wool
fill ~~-1~~~-2~ rex:corruptewool 1 replace wool
fill ~~~1~~~2 rex:corruptedglowstone 1 replace glowstone
fill ~~~-1~~~-2 rex:corruptedglowstone 1 replace glowstone
fill ~1~~~2~~ rex:corruptedglowstone 1 replace glowstone
fill ~-1~~~-2~~ rex:corruptedglowstone 1 replace glowstone
fill ~~1~~~2~ rex:corruptedglowstone 1 replace glowstone
fill ~~-1~~~-2~ rex:corruptedglowstone 1 replace glowstone




