summon lightning_bolt ~5 ~ ~
summon lightning_bolt ~-5 ~ ~
summon lightning_bolt ~ ~ ~5
summon lightning_bolt ~~ ~-5
summon lightning_bolt ~10 ~ ~
summon lightning_bolt ~-10 ~ ~
summon lightning_bolt ~ ~ ~10
summon lightning_bolt ~ ~ ~-10
summon lightning_bolt ~ ~ ~15
summon lightning_bolt ~ ~ ~-15
summon lightning_bolt ~15 ~ ~
summon lightning_bolt ~-15 ~ ~
summon lightning_bolt ~ ~ ~20
summon lightning_bolt ~ ~ ~-20
summon lightning_bolt ~20 ~ ~
summon lightning_bolt ~-20 ~ ~
summon lightning_bolt ~ ~ ~25
summon lightning_bolt ~ ~ ~-25
summon lightning_bolt ~-25 ~ ~
summon lightning_bolt ~25 ~ ~
summon lightning_bolt ~ ~ ~30
summon lightning_bolt ~ ~ ~-30
summon lightning_bolt ~-30 ~ ~
summon lightning_bolt ~30 ~ ~
summon lightning_bolt ~ ~ ~35
summon lightning_bolt ~ ~ ~-35
summon lightning_bolt ~35 ~ ~
summon lightning_bolt ~-35 ~ ~
summon lightning_bolt ~ ~ ~40
summon lightning_bolt ~ ~ ~-40
summon lightning_bolt ~-40 ~ ~
summon lightning_bolt ~40 ~ ~