give @s rex:ironstick
give @s rex:goldenstick
give @s rex:diamondstick
give @s rex:pdiamondpickaxe
give @s rex:pironpickaxe
give @s rex:pgoldpickaxe
give @s rex:pdiamondsword
give @s rex:pgoldsword
give @s rex:pironsword
give @s rex:pironshovel
give @s rex:pgoldaxe
give @s rex:pdiamondshovel
give @s rex:pgoldshovel
give @s rex:pironaxe
give @s rex:pdiamondaxe
give @s rex:pdiamondhoe
give @s rex:pgoldhoe
give @s rex:pironhoe
give @s rex:cironpdiamond
give @s rex:cdiamondpdiamond
give @s rex:cironpgold
give @s rex:cdiamondpgold
give @s rex:cgoldpgold
give @s rex:cgoldpdiamond
give @s rex:cgoldpiron
give @s rex:cdiamondpiron
give @s rex:cironpiron
give @s rex:cironpdiamondpic
give @s rex:cironpgoldenpic
give @s rex:cgoldpdiamondpic
give @s rex:cdiamondpdiamondpic
give @s rex:cgoldpgoldenpic
give @s rex:cgoldpironpic
give @s rex:cdiamondpgoldenpic
give @s rex:cdiamondpironpic
give @s rex:cironpgoldaxe
give @s rex:cironpironpic
give @s rex:cgoldpgoldaxe
give @s rex:stonestick
give @s rex:cdiamondpgoldaxe
give @s rex:stonemold
give @s rex:cablemold
give @s rex:pickaxeheadmold
give @s rex:axheadmold
give @s rex:swordheadmold
give @s rex:hoeheadmold
give @s rex:shovelheadmold
give @s rex:cironpironaxe
give @s rex:cdiamondpironaxe
give @s rex:cgoldpironaxe
give @s rex:cdiamondpdiamondaxe
give @s rex:cdiamondpdiamondshovel
give @s rex:cgoldpdiamondaxe
give @s rex:cgoldpdiamondshovel
give @s rex:cgoldpironshovel
give @s rex:cironpdiamondshovel
give @s rex:cironpironshovel
give @s rex:cironpdiamondaxe
give @s rex:cdiamondpgoldshovel
give @s rex:cgoldpdiamondhoe
give @s rex:cironpdiamondhoe
give @s rex:cgoldpgoldshovel
give @s rex:cdiamondpironshovel
give @s rex:cironpgoldshovel
give @s rex:cdiamondpdiamondhoe
give @s rex:cironpironhoe
give @s rex:cironpgoldhoe
give @s rex:cdiamondpgoldhoe
give @s rex:cdiamondpironhoe
give @s rex:cgoldpironhoe
give @s rex:cgoldpdiamondmobsidian
give @s rex:cgoldpgoldhoe
give @s rex:cironpdiamondmobsidian
give @s rex:cdiamondpdiamondobsidian
give @s rex:cironpgoldmobsidian
give @s rex:cdiamondpgoldmobsidian
give @s rex:cgoldpgoldmobsidian
give @s rex:cironpironmobsidian
give @s rex:cgoldpironmobsidian
give @s rex:cdiamondpironmobisidian
give @s rex:cironpdiamondpicmobsidian
give @s rex:cgoldpdiamondpicmobsidian
give @s rex:cdiamondpdiamondpicmobsidian
give @s rex:cironpgoldenpicmobsidian
give @s rex:cgoldpgoldenpicmobsidian
give @s rex:cironpironpicmobsidian
give @s rex:cdiamondpgoldenpicmobsidian
give @s rex:cdiamondpironpicmobsidian
give @s rex:cgoldpironpicmobsidian
give @s rex:blackessence
give @s rex:cironpgoldaxeobsdian
give @s rex:cgoldpgoldaxemobsidian
give @s rex:cdiamondpgoldaxemobsidian
give @s rex:cdiamondpironaxemobsdian
give @s rex:cgoldpironaxemobsidian
give @s rex:cgoldpdiamondaxemobsidian
give @s rex:cironpironaxemobsidian
give @s rex:cironpdiamondaxemobsidian
give @s rex:cdiamondpdiamondaxemobsidian
give @s rex:cdiamondpdiamondshovelmobsidian
give @s rex:cironpdiamondshovelmobsidian
give @s rex:cgoldpdiamondshovelmobsidian
give @s rex:cironpironshovelmobsidian
give @s rex:cgoldpironshovelmobsidian
give @s rex:cdiamondpironshovelmobsidian
give @s rex:cgoldpgoldshovelmobsidian
give @s rex:cironpgoldshovelmobsdian
give @s rex:cdiamondpgoldshovelmobsidian
give @s rex:sphereofdarkness
give @s rex:wickedcrystal
give @s rex:cdiamondpdiamondhoemobsidian
give @s rex:cgoldpdiamondhoemobsdian
give @s rex:cironpironhoemobsidian
give @s rex:cironpdiamondhoemobsidian
give @s rex:cdiamondpironhoemobsidian
give @s rex:cgoldpironhoemobsidian
give @s rex:cironpgoldhoemobsidian
give @s rex:cdiamondpgoldhoemobsidian
give @s rex:cgoldpgoldhoemobsidian
give @s rex:cgoldpdiamondmcrystal
give @s rex:cdiamondpdiamondmcrystal
give @s rex:cironpdiamondmcrystal
give @s rex:cdiamondpgoldmcrystal
give @s rex:cironpironmcrystal
give @s rex:cironpgoldmcrystal
give @s rex:cgoldpgoldmcrystal
give @s rex:cgoldpironmcrystal
give @s rex:cgoldpdiamondmobsidianmcrystal
give @s rex:cironpdiamondmobsidiancrystal
give @s rex:cdiamondpironmcrystal
give @s rex:cdiamondpdiamondobsidianmcrystal
give @s rex:cironpgoldmobsidianmcrystal
give @s rex:cironpironmobsidianmcrystal
give @s rex:cdiamondpgoldmobsidianmcrystal
give @s rex:cgoldpgoldmobsidianmcrystal
give @s rex:cgoldpironmobsidianmobsidian
give @s rex:cdiamondpironmobisidianmcrystal
give @s rex:cironpdiamondpicmredstone
give @s rex:cgoldpgoldenpicmredstone
give @s rex:cgoldpdiamondpicmredstone
give @s rex:cdiamondpdiamondpicmredstone
give @s rex:cironpgoldenpicmredstone
give @s rex:cdiamondpironpicmredstone
give @s rex:cironpironpicmredstone
give @s rex:cdiamondpgoldenpicmredstone
give @s rex:cgoldpironpicmredstone
give @s rex:cgoldpdiamondpicmobsidianmredstone
give @s rex:cdiamondpdiamondpicmobsidianmredstone
give @s rex:cironpdiamondpicmobsidianmredstone
give @s rex:cironpgoldenpicmobsidianmredstone
give @s rex:cgoldpgoldenpicmobsidianmredstone
give @s rex:cdiamondpgoldenpicmobsidianmredstone
give @s rex:cironpironpicmobsidianmredstone
give @s rex:cdiamondpironpicmobsidianmredstone
give @s rex:cgoldpgoldaxemredstone
give @s rex:cgoldpironpicmobsidianmredstone
give @s rex:cironpgoldaxemredstone
give @s rex:cdiamondpironaxemredstone
give @s rex:cdiamondpgoldaxemredstone
give @s rex:cgoldpironaxemredstone
give @s rex:cironpironaxemredstone
give @s rex:cgoldpdiamondaxemredstone
give @s rex:cironpdiamondaxemredstone
give @s rex:cdiamondpdiamondaxemredstone
give @s rex:astralore
give @s rex:cironpironaxemobsidianmredstone
give @s rex:cdiamondpironaxemobsdianmredstone
give @s rex:cgoldpironaxemobsidianmredstone
give @s rex:cgoldpdiamondaxemobsidianmredstone
give @s rex:cironpdiamondaxemobsidianmredstone
give @s rex:cgoldpdiamondshovelmredstone
give @s rex:cdiamondpdiamondshovelmredstone
give @s rex:cironpdiamondshovelmredstone
give @s rex:cdiamondpdiamondaxemobsidianmredstone
give @s rex:cironpironshovelmredstone
give @s rex:cgoldpgoldshovemredstone
give @s rex:cdiamondpironshovelmredstone
give @s rex:cgoldpironshovelmredstone
give @s rex:cironpgoldshovelmredstone
give @s rex:cdiamondpdiamondshovelmobsidianmredstone
give @s rex:cdiamondpgoldshovelmredstone
give @s rex:cgoldpironshovelmobsidianmredstone
give @s rex:cironpdiamondshovelmobsidianmredstone
give @s rex:cgoldpdiamondshovelmobsidianmredstone
give @s rex:cironpironshovelmobsidianmredstone
give @s rex:cdiamondpironshovelmobsidianmredstone
give @s rex:cgoldpgoldshovelmobsidianmredstone
give @s rex:cdiamondpgoldshovelmobsidianmredstone
give @s rex:cironpgoldshovelmobsdianmredstone
give @s rex:cironpdiamondhoemredstone
give @s rex:cdiamondpdiamondhoemredstone
give @s rex:cgoldpdiamondhoemredstone
give @s rex:cironpironhoemredstone
give @s rex:cgoldpironhoemredstone
give @s rex:cdiamondpironhoemredstone
give @s rex:cdiamondpgoldhoemredstone
give @s rex:cironpgoldhoemredstone
give @s rex:cironpdiamondhoemobsidianmredstone
give @s rex:cgoldpgoldhoemredstone
give @s rex:cdiamondpdiamondhoemobsidianmredstone
give @s rex:cgoldpironhoemobsidianmredstone
give @s rex:cgoldpdiamondhoemobsdianmredstone
give @s rex:cironpironhoemobsidianmredstone
give @s rex:cironpgoldhoemobsidianmredstone
give @s rex:cdiamondpgoldhoemobsidianmredstone
give @s rex:cdiamondpironhoemobsidianmredstone
give @s rex:cgoldpgoldhoemobsidianmredstone
give @s rex:astral
give @s rex:astralstick
give @s rex:castralpdiamond
give @s rex:castralpgold
give @s rex:castralpgoldmcristal
give @s rex:castralpiron
give @s rex:castralpdiamondmcrystal
give @s rex:castralpdiamondmobsidianmcrystal
give @s rex:castralpdiamondmobsidian
give @s rex:castralpironmobsidian
give @s rex:castralpgoldmobsidian
give @s rex:castralpironmcrystal
give @s rex:castralpgoldmobsidianmcrystal
give @s rex:castralpironmobsidianmcrystal
give @s rex:castralpironpic
give @s rex:castralpgoldenpic
give @s rex:castralpdiamondaxe
give @s rex:castralpdiamondpicmredstone
give @s rex:castralpironaxe
give @s rex:castralpgoldaxe
give @s rex:castralpdiamondpic
give @s rex:castralpgoldenpicmredstone
give @s rex:castralpironpicmredstone
give @s rex:castralpironaxemredstone
give @s rex:castralpgoldaxemredstone
give @s rex:castralpdiamondaxemredstone
give @s rex:castralpdiamondpicmobsidian
give @s rex:castralpironpicmobsidian
give @s rex:castralpgoldenpicmobsidian
give @s rex:castralpdiamondpicmobsidianmredstone
give @s rex:castralpgoldenpicmobsidianmredstone
give @s rex:castralpironpicmobsidianmredstone
give @s rex:castralpgoldaxemobsidian
give @s rex:castralpgoldaxemobsidianmredstone
give @s rex:castralpdiamondaxemobsidian
give @s rex:castralpironaxemobsidian
give @s rex:castralpdiamondaxemobsidianmredstone
give @s rex:castralpironaxemobsidianmredstone
give @s rex:castralpironshovel
give @s rex:castralpgoldshovel
give @s rex:castralpdiamondshovel
give @s rex:castralpdiamondhoe
give @s rex:castralpironshovelmredstone
give @s rex:castralpironhoe
give @s rex:castralpdiamondshovelmredstone
give @s rex:castralpgoldhoe
give @s rex:castralpdiamondhoemredstone
give @s rex:castralpgoldshovelmredstone
give @s rex:castralpironhoemredstone
give @s rex:castralpgoldhoemredstone
give @s rex:castralpironhoemobsidian
give @s rex:castralpdiamondshovelmobsidian
give @s rex:castralpironshovelmobsidian
give @s rex:castralpdiamondhoemobsidian
give @s rex:castralpgoldhoemobsidian
give @s rex:castralpgoldshovelmobsidian
give @s rex:castralpironshovelmobsidianmredstone
give @s rex:castralpdiamondshovelmobsidianmredstone
give @s rex:castralpgoldshovelmobsidianmredstone
give @s rex:castralpironhoemobsidianmredstone
give @s rex:castralpdiamondhoemobsidianmredstone
give @s rex:pastralsword
give @s rex:castralpgoldhoemobsidianmredstone
give @s rex:cironpastralmcrystal
give @s rex:cgoldpastralmcrystal
give @s rex:cdiamondpastralmcrystal
give @s rex:castralpastral
give @s rex:cdiamondpastral
give @s rex:castralpastralmcrystal
give @s rex:cironpastral
give @s rex:cgoldpastral
give @s rex:cdiamondpastralmobsidian
give @s rex:cironpastralmobsidian
give @s rex:castralpastralmredstone
give @s rex:cgoldpastralmobsidian
give @s rex:cgoldpastralpic
give @s rex:cdiamondpastralpic
give @s rex:cironpastralpic
give @s rex:pastralpickaxe
give @s rex:castralpastralpic
give @s rex:cgoldpastralpicmredstone
give @s rex:cironpastralpicmredstone
give @s rex:castralpastralpicmredstone
give @s rex:cdiamondpastralpicmredstone
give @s rex:cironpastralpicmobsidian
give @s rex:cgoldpastralpicmobsidian
give @s rex:castralpastralpicmobsidian
give @s rex:cdiamondpastralpicmobsidian
give @s rex:cironpastralaxe
give @s rex:cironpastralaxemredstone
give @s rex:pastralaxe
give @s rex:cgoldpastralaxemredstone
give @s rex:cgoldpastralaxe
give @s rex:castralpastralaxe
give @s rex:cdiamantpastralaxe
give @s rex:cdiamantpastralaxemredstone
give @s rex:cironpastralaxemobsidian
give @s rex:castralpastralaxemredstone
give @s rex:cgoldpastralaxemobsidian
give @s rex:castralpastralaxemobsidian
give @s rex:cdiamondpastralshovel
give @s rex:pastralshovel
give @s rex:cdiamantpastralaxemobsidian
give @s rex:cironpastralshovel
give @s rex:cironpastralshovelmredstone
give @s rex:castralpastralshovel
give @s rex:cdiamondpastralshovelmredstone
give @s rex:cgoldpastralshovelmredstone
give @s rex:castralpastralshovelmredstone
give @s rex:cgoldpastralshovel
give @s rex:cdiamondpastralshovelmobsidian
give @s rex:cgoldpastralshovelmobsidian
give @s rex:castralpastralshovelmobsidian
give @s rex:cironpastralshovelmobisidian
give @s rex:cdiamondastralhoe
give @s rex:pastralhoe
give @s rex:cgoldastralhoe
give @s rex:cironastralhoe
give @s rex:castralastralhoe
give @s rex:cdiamondastralhoemredstone
give @s rex:cgoldastralhoemredstone
give @s rex:castralastralhoemredstone
give @s rex:cironastralhoemredstone
give @s rex:cdiamondastralhoemobsidian
give @s rex:cgoldastralhoemobsidian
give @s rex:cironastralhoemobsidian
give @s rex:castralastralhoemobsidian
give @s rex:toolsguide
give @s rex:redstonesword
give @s rex:emeraldsword
give @s rex:netherrrackswordt1
give @s rex:obsidiansword
give @s rex:flysword
give @s rex:phantonsword
give @s rex:lifesword
give @s rex:amethystsword
give @s rex:lightning_sword
give @s rex:watersword
give @s rex:nethersword
give @s rex:sticksword
give @s rex:firesword
give @s rex:glowstone
give @s rex:endsword
give @s rex:coalsword
give @s rex:stonesword
give @s rex:leavessword
give @s rex:milksword
give @s rex:deepslatesword
give @s rex:desertsword
give @s rex:bom
give @s rex:tntsword
give @s rex:snowsword
give @s rex:grasssword
give @s rex:golensword
give @s rex:lazulisword
give @s rex:farmersword
give @s rex:slimesword
give @s rex:greensword
give @s rex:yellowsword
give @s rex:bluesword
give @s rex:redsword
give @s rex:minersword
give @s rex:stornsword
give @s rex:blacksword
give @s rex:glasssword
give @s rex:batsword
give @s rex:zombiesword
give @s rex:prismarinesword
give @s rex:lavasword
give @s rex:netherstarsword
give @s rex:rainbowsword
give @s rex:neonsword
give @s rex:witchsword
give @s rex:midassword
give @s rex:creepersword
give @s rex:bambusword
give @s rex:browsword
give @s rex:swordofblindness
give @s rex:enderpearlsword
give @s rex:anvilsword
give @s rex:icessword
give @s rex:damagesword
give @s rex:dirtsword
give @s rex:shulkersword
give @s rex:endstonesword
give @s rex:oceansword
give @s rex:necromancersword
give @s rex:clonesword
give @s rex:cactussword
give @s rex:mineblock
give @s rex:soulsword
give @s rex:portalsword
give @s rex:cakesword
give @s rex:minesword
give @s rex:clocksword
give @s rex:swordofspeed
give @s rex:quartzsword
give @s rex:bricksword
give @s rex:websword
give @s rex:sweetbarrysword
give @s rex:mobspawnersword
give @s rex:magneticsword
give @s rex:dioritesword
give @s rex:bedrocksword
give @s rex:granitesword
give @s rex:powerofzeus
give @s rex:lightsword
give @s rex:evokersword
give @s rex:firefire
give @s rex:andesitesword
give @s rex:invisiblesword
give @s rex:firerainsword
give @s rex:herosword
give @s rex:tntrainsword
give @s rex:clearningsword
give @s rex:swordofnature
give @s rex:leathersword
give @s rex:cookiesword
give @s rex:withersword
give @s rex:flintsword
give @s rex:vampiresword
give @s rex:kelpsword
give @s rex:xpsword
give @s rex:eggsword
give @s rex:netherwartsword
give @s rex:rottensword
give @s rex:frozensword
give @s rex:sandstonesword
give @s rex:bonesword
give @s rex:potionsword
give @s rex:skeletonbossblock
give @s rex:coppersword
give @s rex:uptable
give @s rex:acai
give @s rex:brasilianita
give @s rex:acaileaves
give @s rex:brasilianitapickaxe
give @s rex:brasilianitaaxe
give @s rex:brasialianitasword
give @s rex:brasilianitahoe
give @s rex:saciscap
give @s rex:brasilianitashovel
give @s rex:saciperereinpot
give @s rex:terroroftheseas
give @s rex:acaiinthebowl
give @s rex:corruptnugget
give @s rex:corrupteddirt
give @s rex:witherleaves
give @s rex:corruptedsteelingot
give @s rex:corruptedgrass
give @s rex:corruptedlog
give @s rex:corruptedcobblestone
give @s rex:corruptedsand
give @s rex:corruptedglass
give @s rex:corruptedstone
give @s rex:corruptedcraftingtable
give @s rex:corruptedplanks
give @s rex:corruptedslab
give @s rex:corruptedstick
give @s rex:corruptedsteelore
give @s rex:corruptedsteelrae
give @s rex:corruptedsteelhelmet
give @s rex:corruptedsteelsword
give @s rex:corruptedsteelchestplate
give @s rex:corruptedsteelboots
give @s rex:corruptedsteelleggings
give @s rex:corruptedgravel
give @s rex:corruptedice
give @s rex:corruptedclay
give @s rex:corruptedbookshelf
give @s rex:corruptedsandstone
give @s rex:corruptedobsidian
give @s rex:corruptedstairs
give @s rex:corruptedslime
give @s rex:corruptedblock
give @s rex:corruptedsteelblock
give @s rex:puregemore
give @s rex:corruptedsteelpickaxe
give @s rex:puregem
give @s rex:corruptedsteelshovel
give @s rex:corruptedsteelaxe
give @s rex:corruptedsteelhoe
give @s rex:corruptedmushroomstem
give @s rex:corruptedmushroomblock
give @s rex:corruptedconcrete
give @s rex:coblestairs
give @s rex:puregemblock
give @s rex:corruptedgrasspath
give @s rex:corruptedstonebrick
give @s rex:corruptedcobblestondslab
give @s rex:corruptedsandstairs
give @s rex:puregemsword
give @s rex:puregemshovel
give @s rex:puregemaxe
give @s rex:puregempickaxe
give @s rex:puregemhoe
give @s rex:corruptedwool
give @s rex:corruptedrawmeat
give @s rex:corruptedstring
give @s rex:corruptedglowstone
give @s rex:puregemhelmet
give @s rex:corruptedglowstonedust
give @s rex:puregemchestplate
give @s rex:puregemleggings
give @s rex:puregemboots
give @s rex:ancientsword
give @s rex:mobbarriersand
give @s rex:mobbarrier
give @s rex:mobsbarrierplanks
give @s rex:mobbarrierdirt
give @s rex:mobbarrierstone
give @s rex:mobbarriercobblestone
give @s rex:mobbarrierredsand
give @s rex:barriergrass
give @s rex:stonepaxel
give @s rex:obsidianhelmet
give @s rex:ironpaxel
give @s rex:goldenpaxel
give @s rex:diamondpaxel
give @s rex:glassingot
give @s rex:glasspickaxe
give @s rex:netheritepaxel
give @s rex:obsidianleggings
give @s rex:obsidianchestplate
give @s rex:ironaiot
give @s rex:diamondaiot
give @s rex:obsidianboots
give @s rex:zombiestatueitem
give @s rex:netheriteaiot
give @s rex:stoneaiot
give @s rex:obsidianingot
give @s rex:goldenaiot
give @s rex:woodenpaxel
give @s rex:portableconduit
give @s rex:zombieheart
give @s rex:woodenaiot
give @s rex:ironbattleaxe
give @s rex:cristalkingsword
give @s rex:goldenbattleaxe
give @s rex:diamondbattleaxe
give @s rex:emeraldbattleaxe
give @s rex:netheritebattleaxe
give @s rex:pillagercoint
give @s rex:co
give @s rex:kingsfavor
give @s rex:mo
give @s rex:mercenaryfavor
give @s rex:arqueiro
give @s rex:arqueiro1
give @s rex:blazeinsigna
give @s rex:aventureiro
give @s rex:creeperinsigna
give @s rex:capitao1
give @s rex:emeraldnugget
give @s rex:diamondhelmet
give @s rex:goldhelmet
give @s rex:capitao
give @s rex:endermaninsigna
give @s rex:guerreiro
give @s rex:heroi1
give @s rex:insignaheroi
give @s rex:heroi
give @s rex:insignaaventureiro
give @s rex:insignaguerreiro
give @s rex:guerreiro1
give @s rex:insignacapitao
give @s rex:insignarei
give @s rex:ironhelmet
give @s rex:netheritehelmet
give @s rex:netheritehelmet1
give @s rex:mercenario
give @s rex:pillagerinsigna
give @s rex:rei
give @s rex:rei1
give @s rex:spiderinsigna
give @s rex:skeletoninsigna
give @s rex:blacksteelore
give @s rex:sucaptain
give @s rex:rawdarksteel
give @s rex:witherinsigna
give @s rex:zumbiinsigna
give @s rex:summonvillager
give @s rex:jadeore
give @s rex:marble
give @s rex:darksteelingot
give @s rex:darksteelpickaxe
give @s rex:jade
give @s rex:darksteelsword
give @s rex:darksteelhoe
give @s rex:brasilianita_chestplate
give @s rex:darksteelaxe
give @s rex:brasilianita_helmet
give @s rex:darksteelshovel
give @s rex:dark_steel_aiot
give @s rex:dark_steel_battle_axe
give @s rex:dark_steel_paxel
give @s rex:brasilianita_leggings
give @s rex:brasilianita_boots
give @s rex:gem_of_greed
give @s rex:brasilianita_aiot
give @s rex:wicked_gem
give @s rex:power_gem
give @s rex:gem_of_knowledge
give @s rex:magic_gem
give @s rex:brasilianita_paxel
give @s rex:night_vision_helmet
give @s rex:dark_steel_chestplate
give @s rex:dragon_scales
give @s rex:brasilianita_battle_axe
give @s rex:gem_of_immortality
give @s rex:dark_steel_helmet
give @s rex:dark_steel_leggings
give @s rex:dark_steel_boots
give @s rex:shine_ore
give @s rex:pure_gem_paxel
give @s rex:pure_gem_aiot
give @s rex:pure_gem_battle_axe
give @s rex:astral_helmet
give @s rex:temporary_work_table_item
give @s rex:shinebar
give @s rex:temporary_crafting_table
give @s rex:astral_chestplate
give @s rex:astral_leggings
give @s rex:astral_boots
give @s rex:astral_sword
give @s rex:astral_axe
give @s rex:raw_shine_ore
give @s rex:astral_pickaxe
give @s rex:astral_shovel
give @s rex:pillagersummonsguard
give @s rex:astral_aiot
give @s rex:astral_paxel
give @s rex:astral_battle_axe
give @s rex:helmet_lantern
give @s rex:astral_hoe
give @s rex:wither_power
give @s rex:emerald_pickaxe
give @s rex:emerald_axe
give @s rex:emerald_shovel
give @s rex:emerald_helmet
give @s rex:emerald_chestplate
give @s rex:emerald_leggings
give @s rex:emerald_boots
give @s rex:emerald_hoe
give @s rex:emerald_paxel
give @s rex:emerald_aiot
give @s rex:corrupted_steel_battle_axe
give @s rex:corrupted_steel_aiot
give @s rex:shards_of_marble
give @s rex:corrupted_steel_paxel
give @s rex:bar_from_beyond
give @s rex:sphere_of_light
give @s rex:essence_of_the_beyond
give @s rex:helmet_from_beyond
give @s rex:stick_from_beyond
give @s rex:sword_from_beyond
give @s rex:pickaxe_from_bayond
give @s rex:leggings_from_beyond
give @s rex:chestplate_from_beyond
give @s rex:shovel_from_beyond
give @s rex:boots_from_beyond
give @s rex:hoe_from_beyond
give @s rex:axe_from_beyond
give @s rex:paxel_from_beyond
give @s rex:pure_gem_necklace
give @s rex:jade_hoe
give @s rex:jade_sword
give @s rex:jade_pickaxe
give @s rex:jade_shovel
give @s rex:jade_axe
give @s rex:aventureiro1
give @s rex:jade_chestplate
give @s rex:jade_helmet
give @s rex:jade_aiot
give @s rex:jade_battle_axe
give @s rex:jade_paxel
give @s rex:jade_boots
give @s rex:jade_leggings
give @s rex:shine_helmet
give @s rex:shine_chestplate
give @s rex:shine_boots
give @s rex:shibe_leggings
give @s rex:fire_boots
give @s rex:fire_stone
give @s rex:battle_axe_of_beyond
give @s rex:herobrine_insign
give @s rex:shine_sword
give @s rex:shine_pickaxe
give @s rex:shine_hoe
give @s rex:shine_shovel
give @s rex:dragon_helmet
give @s rex:shine_battle_axe
give @s rex:dragon_leggings
give @s rex:dragon_boots
give @s rex:dragon_chestplate
give @s rex:shine_axe
give @s rex:shine_paxel
give @s rex:shine_aiot
give @s rex:portal_frame_on
give @s rex:orb_of_purification
give @s rex:portal_frame_off
give @s rex:tp_block
give @s rex:sr_thankas_insigna
give @s rex:notch_sword
give @s rex:herobrine_sword
give @s rex:desejo
give @s rex:herobrine_beef
give @s rex:regeneration_necklace
give @s rex:magic_off
give @s rex:darkrainbowsword
give @s rex:magic_on
give @s rex:effect_stone_jump_boost
give @s rex:effect_stone_slow_fall
give @s rex:effect_stone_empty
give @s rex:effect_stone_strength
give @s rex:effect_stone_regeneration
give @s rex:effect_stone_speed
give @s rex:effect_stone_water_breathing
give @s rex:stone_effect_night_vision
give @s rex:stone_effect_fire_resistance
give @s rex:golden_ring
give @s rex:potion_ring_jump_boost
give @s rex:stone_effect_resistance
give @s rex:potion_ring_slow_falling
give @s rex:potion_ring_strength
give @s rex:potion_ring_water_breathing
give @s rex:potion_ring_speed
give @s rex:potion_ring_regeneration
give @s rex:potion_ring_fire_resistance
give @s rex:potion_ring_night_vision
give @s rex:potion_ring_resistance
give @s rex:notch_power
give @s rex:potion_ring_all
give @s rex:summon_sob
give @s rex:summon_clones
give @s rex:villager_army_clone
give @s rex:summon_icewitch
give @s rex:animals_summon
give @s rex:corrupted_mobssummon
give @s rex:exit_spawn_menu
give @s rex:magic_stone
give @s rex:regeneration_wand
give @s rex:lightning_wand
give @s rex:lightning_stone
give @s rex:more_powers
give @s rex:tnt_rain
give @s rex:exit_more_powers_menu
give @s rex:ore_rain
give @s rex:earthquake
give @s rex:potion_effects
give @s rex:lightning_explosion
give @s rex:exit_powers
give @s rex:timeandweatherpower
give @s rex:daynight
give @s rex:exittimeandweathermenu
give @s rex:time_speed_on
give @s rex:time_speed_off
give @s rex:tpitems
give @s rex:jump_boost
give @s rex:weather_clear
give @s rex:weather_rain
give @s rex:weather_thunder
give @s rex:health_boost
give @s rex:fireresistance
give @s rex:haste
give @s rex:invisibility
give @s rex:resistance
give @s rex:night_vision
give @s rex:regeneration
give @s rex:speed
give @s rex:water_breathing
give @s rex:village_hero
give @s rex:strength
give @s rex:power_effects
give @s rex:exitpotionmenu
give @s rex:xp_orb1
give @s rex:basic_guide
give @s rex:brasilianitaore
