fill ~~~1~~~2 rex:corruptedlog 1 replace log
fill ~~~-1~~~-2 rex:corruptedlog 1 replace log
fill ~1~~~2~~ rex:corruptedlog 1 replace log
fill ~-1~~~-2~~ rex:corruptedlog 1 replace log
fill ~~1~~~2~ rex:corruptedlog 1 replace log
fill ~~-1~~~-2~ rex:corruptedlog 1 replace log
fill ~~~1~~~2 rex:corruptedgrass 1 replace grass
fill ~~~-1~~~-2 rex:corruptedgrass 1 replace grass
fill ~1~~~2~~ rex:corruptedgrass 1 replace grass
fill ~-1~~~-2~~ rex:corruptedgrass 1 replace grass
fill ~~1~~~2~ rex:corruptedgrass 1 replace grass
fill ~~-1~~-2~ rex:corruptedgrass 1 replace grass
fill ~~~1~~~2 rex:corrupteddirt 1 replace dirt
fill ~~~-1~~~-2 rex:corrupteddirt 1 replace dirt
fill ~1~~~2~~ rex:corrupteddirt 1 replace dirt
fill ~-1~~~-2~~ rex:corrupteddirt 1 replace dirt
fill ~~1~~~2~ rex:corrupteddirt 1 replace dirt
fill ~~-1~~~-2~ rex:corrupteddirt 1 replace dirt
fill ~~~1~~~2 rex:witherleaves 1 replace leaves
fill ~~~-1~~~-2 rex:witherleaves 1 replace leaves
fill ~1~~~2~~ rex:witherleaves 1 replace leaves
fill ~-1~~~-2~~ rex:witherleaves 1 replace leaves
fill ~~1~~~2~ rex:witherleaves 1 replace leaves
fill ~~-1~~~-2~ rex:witherleaves 1 replace leaves
fill ~~~1~~~2 rex:corruptedstone 1 replace stone
fill ~~~-1~~~-2 rex:corruptedstone 1 replace stone
fill ~1~~~2~~ rex:corruptedstone 1 replace stone
fill ~-1~~~-2~~ rex:corruptedstone 1 replace stone
fill ~~1~~~2~ rex:corruptedstone 1 replace stone
fill ~~-1~~~-2~ rex:corruptedstone 1 replace stone
fill ~~~1~~~2 rex:corruptedcobblestone 1 replace cobblestone
fill ~~~-1~~~-2 rex:corruptedcobblestone 1 replace cobblestone
fill ~1~~~2~~ rex:corruptedcobblestone 1 replace cobblestone
fill ~-1~~~-2~~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~1~~~2~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~-1~~~-2~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~~1~~~2 rex:corruptedsand 1 replace sand
fill ~~~-1~~~-2 rex:corruptedsand 1 replace sand
fill ~1~~~2~~ rex:corruptedsand 1 replace sand
fill ~-1~~~-2~~ rex:corruptedsand 1 replace sand
fill ~~1~~~2~ rex:corruptedsand 1 replace sand
fill ~~-1~~~-2~ rex:corruptedsand 1 replace sand
fill ~~~1~~~2 rex:corruptedlog 2 replace log
fill ~~~-1~~~-2 rex:corruptedlog 2 replace log
fill ~1~~~2~~ rex:corruptedlog 2 replace log
fill ~-1~~~-2~~ rex:corruptedlog 2 replace log
fill ~~1~~~2~ rex:corruptedlog 2 replace log
fill ~~-1~~~-2~ rex:corruptedlog 2 replace log
fill ~~~1~~~2 rex:corruptedlog 3 replace log
fill ~~~-1~~~-2 rex:corruptedlog 3 replace log
fill ~1~~~2~~ rex:corruptedlog 3 replace log
fill ~-1~~~-2~~ rex:corruptedlog 3 replace log
fill ~~1~~~2~ rex:corruptedlog 3 replace log
fill ~~-1~~~-2~ rex:corruptedlog 3 replace log
fill ~~~1~~~2 rex:corruptedlog 4 replace log
fill ~~~-1~~~-2 rex:corruptedlog 4 replace log
fill ~1~~~2~~ rex:corruptedlog 4 replace log
fill ~-1~~~-2~~ rex:corruptedlog 4 replace log
fill ~~1~~~2~ rex:corruptedlog 4 replace log
fill ~~-1~~~-2~ rex:corruptedlog 4 replace log
fill ~~~1~~~2 rex:corruptedlog 5 replace log
fill ~~~-1~~~-2 rex:corruptedlog 5 replace log
fill ~1~~~2~~ rex:corruptedlog 5 replace log
fill ~-1~~~-2~~ rex:corruptedlog 5 replace log
fill ~~1~~~2~ rex:corruptedlog 5 replace log
fill ~~-1~~~-2~ rex:corruptedlog 5 replace log
fill ~~~1~~~2 rex:corruptedglass 1 replace glass
fill ~~~-1~~~-2 rex:corruptedglass 1 replace glass
fill ~1~~~2~~ rex:corruptedglass 1 replace glass
fill ~-1~~~-2~~ rex:corruptedglass 1 replace glass
fill ~~1~~~2~ rex:corruptedglass 1 replace glass
fill ~~-1~~~-2~ rex:corruptedglass 1 replace glass
fill ~~~1~~~2 rex:corruptedlog 1 replace log2
fill ~~~-1~~~-2 rex:corruptedlog 1 replace log2
fill ~1~~~2~~ rex:corruptedlog 1 replace log2
fill ~-1~~~-2~~ rex:corruptedlog 1 replace log2
fill ~~1~~~2~ rex:corruptedlog 1 replace log2
fill ~~-1~~~-2~ rex:corruptedlog 1 replace log2
fill ~~~1~~~2 rex:corruptedcraftingtable 1 replace crafting_table
fill ~~~-1~~~-2 rex:corruptedcraftingtable 1 replace crafting_table
fill ~1~~~2~~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~-1~~~-2~~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~1~~~2~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~-1~~~-2~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~~1~~~2 rex:corruptedplanks 1 replace planks
fill ~~~-1~~~-2 rex:corruptedplanks 1 replace planks
fill ~1~~~2~~ rex:corruptedplanks 1 replace planks
fill ~-1~~~-2~~ rex:corruptedplanks 1 replace planks
fill ~~1~~~2~ rex:corruptedplanks 1 replace planks
fill ~~-1~~~-2~ rex:corruptedplanks 1 replace planks