fill ~~~1~~~2 rex:corruptedlog 1 replace log
fill ~~~-1~~~-2 rex:corruptedlog 1 replace log
fill ~1~~~2~~ rex:corruptedlog 1 replace log
fill ~-1~~~-2~~ rex:corruptedlog 1 replace log
fill ~~1~~~2~ rex:corruptedlog 1 replace log
fill ~~-1~~~-2~ rex:corruptedlog 1 replace log
fill ~~~1~~~2 rex:corruptedgrass 1 replace grass
fill ~~~-1~~~-2 rex:corruptedgrass 1 replace grass
fill ~1~~~2~~ rex:corruptedgrass 1 replace grass
fill ~-1~~~-2~~ rex:corruptedgrass 1 replace grass
fill ~~1~~~2~ rex:corruptedgrass 1 replace grass
fill ~~-1~~-2~ rex:corruptedgrass 1 replace grass
fill ~~~1~~~2 rex:corrupteddirt 1 replace dirt
fill ~~~-1~~~-2 rex:corrupteddirt 1 replace dirt
fill ~1~~~2~~ rex:corrupteddirt 1 replace dirt
fill ~-1~~~-2~~ rex:corrupteddirt 1 replace dirt
fill ~~1~~~2~ rex:corrupteddirt 1 replace dirt
fill ~~-1~~~-2~ rex:corrupteddirt 1 replace dirt
fill ~~~1~~~2 rex:witherleaves 1 replace leaves
fill ~~~-1~~~-2 rex:witherleaves 1 replace leaves
fill ~1~~~2~~ rex:witherleaves 1 replace leaves
fill ~-1~~~-2~~ rex:witherleaves 1 replace leaves
fill ~~1~~~2~ rex:witherleaves 1 replace leaves
fill ~~-1~~~-2~ rex:witherleaves 1 replace leaves
fill ~~~1~~~2 rex:corruptedstone 1 replace stone
fill ~~~-1~~~-2 rex:corruptedstone 1 replace stone
fill ~1~~~2~~ rex:corruptedstone 1 replace stone
fill ~-1~~~-2~~ rex:corruptedstone 1 replace stone
fill ~~1~~~2~ rex:corruptedstone 1 replace stone
fill ~~-1~~~-2~ rex:corruptedstone 1 replace stone
fill ~~~1~~~2 rex:corruptedcobblestone 1 replace cobblestone
fill ~~~-1~~~-2 rex:corruptedcobblestone 1 replace cobblestone
fill ~1~~~2~~ rex:corruptedcobblestone 1 replace cobblestone
fill ~-1~~~-2~~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~1~~~2~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~-1~~~-2~ rex:corruptedcobblestone 1 replace cobblestone
fill ~~~1~~~2 rex:corruptedsand 1 replace sand
fill ~~~-1~~~-2 rex:corruptedsand 1 replace sand
fill ~1~~~2~~ rex:corruptedsand 1 replace sand
fill ~-1~~~-2~~ rex:corruptedsand 1 replace sand
fill ~~1~~~2~ rex:corruptedsand 1 replace sand
fill ~~-1~~~-2~ rex:corruptedsand 1 replace sand
fill ~~~1~~~2 rex:corruptedlog 2 replace log
fill ~~~-1~~~-2 rex:corruptedlog 2 replace log
fill ~1~~~2~~ rex:corruptedlog 2 replace log
fill ~-1~~~-2~~ rex:corruptedlog 2 replace log
fill ~~1~~~2~ rex:corruptedlog 2 replace log
fill ~~-1~~~-2~ rex:corruptedlog 2 replace log
fill ~~~1~~~2 rex:corruptedlog 3 replace log
fill ~~~-1~~~-2 rex:corruptedlog 3 replace log
fill ~1~~~2~~ rex:corruptedlog 3 replace log
fill ~-1~~~-2~~ rex:corruptedlog 3 replace log
fill ~~1~~~2~ rex:corruptedlog 3 replace log
fill ~~-1~~~-2~ rex:corruptedlog 3 replace log
fill ~~~1~~~2 rex:corruptedlog 4 replace log
fill ~~~-1~~~-2 rex:corruptedlog 4 replace log
fill ~1~~~2~~ rex:corruptedlog 4 replace log
fill ~-1~~~-2~~ rex:corruptedlog 4 replace log
fill ~~1~~~2~ rex:corruptedlog 4 replace log
fill ~~-1~~~-2~ rex:corruptedlog 4 replace log
fill ~~~1~~~2 rex:corruptedlog 5 replace log
fill ~~~-1~~~-2 rex:corruptedlog 5 replace log
fill ~1~~~2~~ rex:corruptedlog 5 replace log
fill ~-1~~~-2~~ rex:corruptedlog 5 replace log
fill ~~1~~~2~ rex:corruptedlog 5 replace log
fill ~~-1~~~-2~ rex:corruptedlog 5 replace log
fill ~~~1~~~2 rex:corruptedglass 1 replace glass
fill ~~~-1~~~-2 rex:corruptedglass 1 replace glass
fill ~1~~~2~~ rex:corruptedglass 1 replace glass
fill ~-1~~~-2~~ rex:corruptedglass 1 replace glass
fill ~~1~~~2~ rex:corruptedglass 1 replace glass
fill ~~-1~~~-2~ rex:corruptedglass 1 replace glass
fill ~~~1~~~2 rex:corruptedlog 1 replace log2
fill ~~~-1~~~-2 rex:corruptedlog 1 replace log2
fill ~1~~~2~~ rex:corruptedlog 1 replace log2
fill ~-1~~~-2~~ rex:corruptedlog 1 replace log2
fill ~~1~~~2~ rex:corruptedlog 1 replace log2
fill ~~-1~~~-2~ rex:corruptedlog 1 replace log2
fill ~~~1~~~2 rex:corruptedcraftingtable 1 replace crafting_table
fill ~~~-1~~~-2 rex:corruptedcraftingtable 1 replace crafting_table
fill ~1~~~2~~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~-1~~~-2~~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~1~~~2~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~-1~~~-2~ rex:corruptedcraftingtable 1 replace crafting_table
fill ~~~1~~~2 rex:corruptedslab 1 replace wooden_slab
fill ~~~-1~~~-2 rex:corruptedslab 1 replace wooden_slab
fill ~1~~~2~~ rex:corruptedslab 1 replace wooden_slab
fill ~-1~~~-2~~ rex:corruptedslab 1 replace wooden_slab
fill ~~1~~~2~ rex:corruptedslab 1 replace wooden_slab
fill ~~-1~~~-2~ rex:corruptedslab 1 replace wooden_slab
fill ~~~1~~~2 rex:corruptedplanks 1 replace planks 1
fill ~~~-1~~~-2 rex:corruptedplanks 1 replace planks 1
fill ~1~~~2~~ rex:corruptedplanks 1 replace planks 1
fill ~-1~~~-2~~ rex:corruptedplanks 1 replace planks 1
fill ~~1~~~2~ rex:corruptedplanks 1 replace planks 1
fill ~~-1~~~-2~ rex:corruptedplanks 1 replace planks 1
fill ~~~1~~~2 rex:corruptedsteelore 1 replace iron_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace iron_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace iron_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace iron_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace iron_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace iron_ore
fill ~~~1~~~2 rex:corruptedsteelore 1 replace coal_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace coal_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace coal_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace coal_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace coal_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace coal_ore
fill ~~~1~~~2 rex:corruptedsteelore 1 replace redstone_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace redstone_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace redstone_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace redstone_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace redstone_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace redstone_ore
fill ~~~1~~~2 rex:corruptedsteelore 1 replace gold_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace gold_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace gold_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace gold_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace gold_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace gold_ore
fill ~~~1~~~2 rex:corruptedsteelore 1 replace lapis_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace lapis_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace lapis_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace lapis_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace lapis_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace lapis_ore
fill ~~~1~~~2 rex:corruptedclay 1 replace clay
fill ~~~-1~~~-2 rex:corruptedclay 1 replace clay
fill ~1~~~2~~ rex:corruptedclay 1 replace clay
fill ~-1~~~-2~~ rex:corruptedclay 1 replace clay
fill ~~1~~~2~ rex:corruptedclay 1 replace clay
fill ~~-1~~~-2~ rex:corruptedclay 1 replace clay
fill ~~~1~~~2 rex:corruptedgravel 1 replace gravel
fill ~~~-1~~~-2 rex:corruptedgravel 1 replace gravel
fill ~1~~~2~~ rex:corruptedgravel 1 replace gravel
fill ~-1~~~-2~~ rex:corruptedgravel 1 replace gravel
fill ~~1~~~2~ rex:corruptedgravel 1 replace gravel
fill ~~-1~~~-2~ rex:corruptedgravel 1 replace gravel
fill ~~~1~~~2 rex:corruptedice 1 replace ice
fill ~~~-1~~~-2 rex:corruptedice 1 replace ice
fill ~1~~~2~~ rex:corruptedice 1 replace ice
fill ~-1~~~-2~~ rex:corruptedice 1 replace ice
fill ~~1~~~2~ rex:corruptedice 1 replace ice
fill ~~-1~~~-2~ rex:corruptedice 1 replace ice
fill ~~~1~~~2 rex:corruptedice 1 replace packed_ice
fill ~~~-1~~~-2 rex:corruptedice 1 replace packed_ice
fill ~1~~~2~~ rex:corruptedice 1 replace packed_ice
fill ~-1~~~-2~~ rex:corruptedice 1 replace packed_ice
fill ~~1~~~2~ rex:corruptedice 1 replace packed_ice
fill ~~-1~~~-2~ rex:corruptedice 1 replace packed_ice
fill ~~~1~~~2 rex:corruptedobsidian 1 replace obsidian
fill ~~~-1~~~-2 rex:corruptedobsidian1 replace obsidian
fill ~1~~~2~~ rex:corruptedobsidian 1 replace obsidian
fill ~-1~~~-2~~ rex:corruptedobsidian 1 replace obsidian
fill ~~1~~~2~ rex:corruptedobsidian 1 replace obsidian
fill ~~-1~~~-2~ rex:corruptedobsidian 1 replace obsidian
fill ~~~1~~~2 rex:corruptedsandstone 1 replace sandstone
fill ~~~-1~~~-2 rex:corruptedsandstone1 replace sandstone
fill ~1~~~2~~ rex:corruptedsandstone 1 replace sandstone
fill ~-1~~~-2~~ rex:corruptedsandstone 1 replace sandstone
fill ~~1~~~2~ rex:corruptedsandstone 1 replace sandstone
fill ~~-1~~~-2~ rex:corruptedsandstone 1 replace sandstone
fill ~~~1~~~2 rex:corruptedbookshelf 1 replace book_shelf
fill ~~~-1~~~-2 rex:corruptedbookshelf1 replace book_shelf
fill ~1~~~2~~ rex:corruptedbookshelf 1 replace book_shelf
fill ~-1~~~-2~~ rex:corruptedbookshelf 1 replace book_shelf
fill ~~1~~~2~ rex:corruptedbookshelf 1 replace book_shelf
fill ~~-1~~~-2~ rex:corruptedbookshelf 1 replace book_shelf
fill ~~~1~~~2 rex:corruptedsteelore 1 replace copper_ore
fill ~~~-1~~~-2 rex:corruptedsteelore 1 replace copper_ore
fill ~1~~~2~~ rex:corruptedsteelore 1 replace copper_ore
fill ~-1~~~-2~~ rex:corruptedsteelore 1 replace copper_ore
fill ~~1~~~2~ rex:corruptedsteelore 1 replace copper_ore
fill ~~-1~~~-2~ rex:corruptedsteelore 1 replace copper_ore
fill ~~~1~~~2 rex:corruptedstairs 1 replace oak_stairs
fill ~~~-1~~~-2 rex:corruptedstairs1 replace oak_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace oak_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace oak_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  oak_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace oak_stairs
fill ~~~1~~~2 rex:corruptedstairs 1 replace acacia_stairs
fill ~~~-1~~~-2 rex:corruptedstairs1 replace acacia_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace acacia_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace acacia_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  acacia_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace acacia_stairs
fill ~~~1~~~2 rex:corruptedstairs 1 replace spruce_stairs
fill ~~~-1~~~-2 rex:corruptedstairs1 replace spruce_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace spruce_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace spruce_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  spruce_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace spruce_stairs
fill ~~~1~~~2 rex:corruptedstairs 1 replace birch_stairs
fill ~~~-1~~~-2 rex:corruptedstairs1 replace birch_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace birch_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace birch_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  birch_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace birch_stairs
fill ~~~1~~~2 rex:corruptedstairs 1 replace jungle_stairs
fill ~~~-1~~~-2 rex:corruptedstairs1 replace jungle_stairs
fill ~1~~~2~~ rex:corruptedstairs 1 replace jungle_stairs
fill ~-1~~~-2~~ rex:corruptedstairs 1 replace jungle_stairs
fill ~~1~~~2~ rex:corruptedstairs 1 replace  jungle_stairs
fill ~~-1~~~-2~ rex:corruptedstairs 1 replace jungle_stairs
fill ~~~1~~~2 rex:corruptedslime 1 replace slime
fill ~~~-1~~~-2 rex:corruptedslime1 replace slime
fill ~1~~~2~~ rex:corruptedslime 1 replace slime
fill ~-1~~~-2~~ rex:corruptedslime 1 replace slime
fill ~~1~~~2~ rex:corruptedslime 1 replace  slime
fill ~~-1~~~-2~ rex:corruptedslime 1 replace slime